### ISSUE TITLE
Tooltips for further explanation 

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/community#10]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be beneficial I think to add tooltips through the platform.  Even to a defi users these tips (further detailed explanation) would elevate several questions.  A few examples where they might be handy but isn’t limited to areas below.  #sharing_is_caring #each_one_teach_one  

![image](https://user-images.githubusercontent.com/71201055/114513261-03103f80-9c08-11eb-806f-f9b4643a5be7.png)
![image](https://user-images.githubusercontent.com/71201055/114513282-06a3c680-9c08-11eb-8019-34eca8c576a5.png)
![image](https://user-images.githubusercontent.com/71201055/114513307-0acfe400-9c08-11eb-9332-9c5cd1f08219.png)

**Comment by harveerenergy** [comment]
Internal issue #345 raised

**Comment by hskainth** [comment]
@LearnPolkadot this has been implemented and can now be closed.
