### ISSUE TITLE
Can't see my supply ballance-Can't claim it back

### ISSUE THREAD

**Issue by kontrapunkt88807** [UnFederalReserve/community#100]
**Describe the bug**
07.05.2021 i put 871.031195088236149501 erdsl on supply and after few days when i connected my metamsk it's no longer avaliable.
on etherscan i can see i have 43,545.65350511uneRSDL which is 50:1 ratio to the native token which i deposited..
my etherscan adress is
0x7b70eb7eefa91ccb95ba2cc9da2d161f353f7155
where you can see it. please help me as i whis to put that behind me. 

PLEASE HEEEEELP, IF NOT I WILL HAVE TO POST THIS ON TWITTER FOR SOMEONE TO HELP ME

![Snimka zaslona 2021-10-15 220253](https://user-images.githubusercontent.com/92604404/137547129-1e1dd037-f571-4362-b857-281dd213e6cf.png)
![Snimka zaslona 2021-10-15 220349](https://user-images.githubusercontent.com/92604404/137547132-747b806b-ba57-4d4b-a7de-3d36f95f5f0c.png)
![Snimka zaslona 2021-10-15 220439](https://user-images.githubusercontent.com/92604404/137547133-511f13f0-5a59-414a-9348-35c5c735df69.png)

**Comment by hskainth** [comment]
@kontrapunkt88807 are you still seeing this issue? please try refreshing browser and ensure you are on ethereum mainnet

**Comment by kontrapunkt88807** [comment]
hello! Still nothing. Im on ethereum mainnet and connected my wallet but still nothing.

**Comment by hskainth** [comment]
@kontrapunkt88807 you can use etherscan to withdraw in this instance via the below -

https://etherscan.io/address/0xf908dcd35129fefb01d39685425eca88c3a8a506#writeProxyContract
Connect to web3
20. redeem
Enter 4354565350511
Press Write

**Comment by earthcallingmoon** [comment]
i have same issue. still no help

**Comment by hskainth** [comment]
@kontrapunkt88807 did this work for you?

**Comment by earthcallingmoon** [comment]
No, funds still locked on platform cause of bug

**Comment by hskainth** [comment]
@earthcallingmoon the above question was for @kontrapunkt88807 , we will update shortly to your ticket 102.

**Comment by hskainth** [comment]
Closing issue as no response in almost 2weeks, assume this has been resolved.
