### ISSUE TITLE
Can't withdraw eRSDL from supply side

### ISSUE THREAD

**Issue by interl0per2** [UnFederalReserve/community#101]
**Describe the bug**
I supplied approximately 34k eRSDL several months ago to the platform to earn interest. As that has been sunset, my tokens are now locked on the platform. I am unable to withdraw my tokens on the platform. I have had this issue before on another platform (because I regularly remove approvals for security purposes) where I was unable to withdraw tokens because I had removed the approval for it. Not saying that is the case here, but suggesting it as one.

**To Reproduce**
1) Deposit eRSDL 
2) Remove approval via platform like DeBank
3) Try to withdraw eRSDL with no approval

**Expected behavior**
I expected to see to be able to withdraw my tokens or at least see a button to do so. Check out the screenshot... the withdraw button is greyed out and there is no where to input a number or anything to tell the platform how much to withdraw.

**Screenshots**
![image](https://user-images.githubusercontent.com/92821671/137973602-0ebd4d98-11dd-4f08-9843-4c82a74d27d8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Wallet Version (please complete the following information):**
 - Wallet: Metamask
 - Public Address: 0xf6f78960e9a132868f3fbf1458960dc2325097e3

**Additional context**

**Comment by hskainth** [comment]
@interl0per2 could you please send me screenshot of the supply tab? On the platform token needs to be approved before it can be withdrawn.

**Comment by interl0per2** [comment]
![1](https://user-images.githubusercontent.com/92821671/138018980-2765bb50-9805-4d3b-98f6-0f9ee1845acb.PNG)
![2](https://user-images.githubusercontent.com/92821671/138018987-50517626-a5c2-45e3-8024-b2d94eb43b89.PNG)

1 - What my home screen looks like
2 - There is no ability to enter text in any field and "Withdraw" button is greyed out... I can't click anything.

**Comment by interl0per2** [comment]
![3](https://user-images.githubusercontent.com/92821671/138019135-360acedf-43ee-4b80-9ebb-de804704f3f4.PNG)

**Comment by interl0per2** [comment]
![4](https://user-images.githubusercontent.com/92821671/138019267-3cb00377-cc2b-42cd-9958-d107fc2bf156.PNG)

**Comment by interl0per2** [comment]
> @interl0per2 could you please send me screenshot of the supply tab? On the platform token needs to be approved before it can be withdrawn.

I understand that the token needs to be approved. I have the approvals in place, you don't have the area to write how much I want to withdraw. Tell me where I can specify how much to withdraw.

**Comment by hskainth** [comment]
@interl0per2  Please try again.

**Comment by hskainth** [comment]
@interl0per2 does this now work for you?

**Comment by interl0per2** [comment]
Yes. I was able to withdraw a couple weeks ago. Thanks!

**Comment by hskainth** [comment]
Closing issue as resolved.
