### ISSUE TITLE
says i have no funds but i do, also wont let me see my lended funds or anything else

### ISSUE THREAD

**Issue by earthcallingmoon** [UnFederalReserve/community#102]
i use metamask on a macbook with google chrome 

connected to unfederal reserve lending,
i have connected in the past many times without issue and have unfederal reserve lended out on the platform, i also have more unfederal reserve in my wallet.

when i connect to unfed page now it connects me but says i have zero funds and also wont show me my staked/lended funds. 

i cant unstake, i cant see funds, i cant see options for lending or borrowing, just blank. 

![Screen Shot 2021-10-17 at 5 23 37 PM](https://user-images.githubusercontent.com/92878877/138134301-39541d6f-605e-4bf6-8b9d-591adfd36c93.png)
![Screen Shot 2021-10-17 at 5 23 59 PM](https://user-images.githubusercontent.com/92878877/138134314-2f2346b3-ade8-495e-97d0-1a8931d90aad.png)
![Screen Shot 2021-10-17 at 9 20 44 PM](https://user-images.githubusercontent.com/92878877/138134319-d62ff277-3f4f-43fd-8895-3e8b5f453fec.png)

**Comment by hskainth** [comment]
@earthcallingmoon  Please try again.

**Comment by earthcallingmoon** [comment]
issue still present

**Comment by hskainth** [comment]
@earthcallingmoon Please provide wallet and browser details.

**Comment by earthcallingmoon** [comment]
browser, chrome, wallet i am keeping private, i shared with other tech support before and nothing was done.

**Comment by hskainth** [comment]
Internal issue 1723 raised to investigate.

**Comment by hskainth** [comment]
@earthcallingmoon do you still see same issue on the new site https://app.unfederalreserve.com/ ?

**Comment by hskainth** [comment]
Closing issue as no response for over 2 weeks.
