### ISSUE TITLE
funds stuck on platform fees charged 

### ISSUE THREAD

**Issue by jamesrilett** [UnFederalReserve/community#103]
**Describe the bug**
I have tried to take my ersdl from the supply on the website 2 times, it shows as a success but the ersdl is still on the site and not in my wallet.
This has cost me nearly 100 dollers in fees already so i dont want to keep trying. i have withdrawn from the supply before and it worked but it wont anymore.

**To Reproduce**

**Expected behavior**
The funds should be in my wallet
**Screenshots**
If applicable, add screenshots to help explain your problem

**Deskto
![Screenshot (11
![Screenshot (118)](https://user-images.githubusercontent.com/78909804/138692654-24cd1aa8-ec3e-4f8e-80dc-f586bd017fde.png)
![Screenshot (119)](https://user-images.githubusercontent.com/78909804/138692663-9d2bcccf-e25f-4bd4-9d0d-0c2bcdb7f30a.png)

![Screenshot (116)](https://user-images.githubusercontent.com/78909804/138692595-dcdd4ab6-c2c5-4a5b-9f56-1d27475e9b9
![Screenshot (117)](https://user-images.githubusercontent.com/78909804/138692638-290f1148-44f1-4f83-9465-90c70012cff9.png)
b.png)
5)](https://user-images.githubusercontent.com/78909804/138692586-0f52d287-3776-4d50-a6f8-9de46b6532a3.png)

![Screenshot (113)](
![Screenshot (114)](https://user-images.githubusercontent.com/78909804/138692555-01f1a8b1-0b4a-42b3-a364-63d10681217e.png)
https://user-images.githubusercontent.com/78909804/138692537-453e47ff-470e-4079-992e-80313094bfd0.png)
![Screenshot (112)](https://user-images.githubusercontent.com/78909804/138692489-6c564324-0632-4422-a0d3-972bf7198f40.png)
p (please complete the following information):**
 - OS: [e.g. iOS] Asus sonic master
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] latest version

**Wallet Version (please complete the following information):**
 - Wallet: [e.g. MetaMask, Coinbase] metemask with ledger
 - Public Address: [e.g. 0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7]
0x3A8ba8911dA2A7c0B58C65Ba8ced6BcdE2cA7e8E
**Additional context**

**Comment by hskainth** [comment]
@jamesrilett There is some outstanding debt left (as seen in screenshot and query below looks like eRSDL borrowed) withdrawing a slightly smaller amount should go through.

<img width="431" alt="2021-10-25 at 20 13 28" src="https://user-images.githubusercontent.com/81052004/138741186-e9683474-212a-40b9-bf84-74ece89abfe7.png">

**Comment by jamesrilett** [comment]
Is that not an error on the platform? I payed the max amount when borrowing and shows I have nothing borrowed which has cost nearly 100 dollers up to date to try to withdraw.

**Comment by hskainth** [comment]
@jamesrilett raised an internal bug to triage will update once we have investigated.

**Comment by hskainth** [comment]
Closing issue as resolved.

**Comment by jamesrilett** [comment]
Solved but still a loss of hundred of dollers in fees
