### ISSUE TITLE
Staking Balance Showing As Zero

### ISSUE THREAD

**Issue by lindsaymatcham** [UnFederalReserve/community#104]
Hi,

when connecting my coinbase wallet to the ersdl website the staked balance is showing as zero, despite the unersdl coins being in my coinbase wallet

my ersdl address is : 0x98f4AdCAa301FC99b93c1E727a00bb7301120060

I started staking back in May upon launch

can someone pls help?

**Comment by hskainth** [comment]
@lindsaymatcham is your coinbase wallet on the ethereum mainnet network if connecting via coinbase app to unfederal reserve lending platform?

You can check this by opening the coinbase app and going to settings > Connections > Ethereum should be selected.

Please also try a hard browser reset CTRL  SHIFT  R

**Comment by lindsaymatcham** [comment]
Hi,  yes it's set to Ethereum, and this is is still not working, I have a Mac computer and downloaded chrome and still no luck. Any ideas?

**Comment by hskainth** [comment]
Internal issue #1695 raised to investigate this.

**Comment by lindsaymatcham** [comment]
Thanks v much, but worried at this point so appreciate the help

**Comment by lindsaymatcham** [comment]
Any luck on this pls?

**Comment by vladyslav2** [comment]
@lindsaymatcham can you clarify are you talking about https://lending.unfederalreserve.com/ or about  https://app.unfederalreserve.com/ ?

**Comment by lindsaymatcham** [comment]
I'm staking my ersdl on the platform and I have unersdl in my coinbase wallet as proof of that.  I staked back in May.  However when I connect my coinbase wallet to the website there are no balances on the website

**Comment by lindsaymatcham** [comment]
I thought I staked on the first link? What is the difference between links?

**Comment by lindsaymatcham** [comment]
I staked on the first link

**Comment by lindsaymatcham** [comment]
Any luck?

**Comment by lindsaymatcham** [comment]
Hello?

**Comment by hskainth** [comment]
@lindsaymatcham we are looking into your query and will update after investigation.

**Comment by hskainth** [comment]
@lindsaymatcham could you please try the below -

1.  Open https://etherscan.io/address/0xe4cc5a22b39ffb0a56d67f94f9300db20d786a5f#writeProxyContract
2.  Click connect to Web3, connect the wallet
3.  Choose redeem function
4.  Enter 30801362773513
5.  Click redeem
6.  Click write
7.  Approve the transaction in metamask

![141164347-60c3370d-dd74-4e3a-a26c-fb2fb91f16ff](https://user-images.githubusercontent.com/81052004/141462482-2554942c-a854-4256-a13b-0820369f901c.png)

**Comment by lindsaymatcham** [comment]
Doesn't seem to be an option to connect coinbase wallet? Loads of wallets there but not coinbase

**Comment by lindsaymatcham** [comment]
Thoughts?

**Comment by lindsaymatcham** [comment]
Need an answer on this please

**Comment by lindsaymatcham** [comment]
Guys. Can someone please get back to me?

**Comment by hskainth** [comment]
@lindsaymatcham could you please let me know if you still see this on the new site https://app.unfederalreserve.com/ ?

**Comment by lindsaymatcham** [comment]
Hi mate it's working on mobile
Now thanks very much

**Comment by lindsaymatcham** [comment]
Appreciate your help

**Comment by hskainth** [comment]
Closing issue as resolved.
