### ISSUE TITLE
Unable to Unstake Legacy eRSDL Tokens

### ISSUE THREAD

**Issue by mkm703** [UnFederalReserve/community#105]
**Describe the bug**
Recently, I finally decided to get my Legacy eRSDL tokens unstaked and restaked on the new contract.

First, I paid off the following outstanding Borrows I had through the platform:

~$8,300 in USDC loans (Tx: 0x6e7f89ab726a60410d4d6f1c736ab7fd0053db3bffa7901b314da10ca584ad6e)
~$225 in USDT loans (Tx: 0xaebcef9de8c62bac4148e37d6a1b969262677548e969d7bf95c8b0cd831c97ff
I even attempted to repay the dust left on an old ETH loan (Tx: 0x08b296d2496568088ea724244c4f7aac0edd0d33b0e44f43fbc01e8a1ce25988

After performing all of these tasks, I attempted to unstake my eRSDL tokens (the only Supply token I had on Reserve Lending). However, when I attempted to Withdraw, the "processing" symbol on the Withdraw button in the dialog box simply spins. No prompt to approve the transaction within my MetaMask wallet is provided. 

I understand I still have a small amount of ETH dust, so I even attempted to remove only a portion of my staked tokens, but it was unsuccessful. I attempted various percentages from 25-95% with no success, all with round numbers (no long decimal chains).

I have also disconnected and reconnected my wallet, closed and reopened my browser, and even rebooted my PC. Please let me know if you have any insights, and thank you very much for your help!

**To Reproduce**

**Expected behavior**
I expected that when my Borrows were repaid I would be able to unstake my tokens. 

**Screenshots**
![Screenshot 2021-11-28 181023](https://user-images.githubusercontent.com/95192462/143790080-41068641-db3b-4268-844e-eab3796b0b32.png)

![Screenshot 2021-11-28 181138](https://user-images.githubusercontent.com/95192462/143790117-b53e9157-caf7-4795-bcb6-4fa8d408dd1b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, Version 21H1
 - Browser: Chrome
 - Browser Version: 95.0.4638.69

**Wallet Version (please complete the following information):**
 - Wallet: MetaMask
 - Public Address: 0x63Aaeba9d2ebCF6588a39BeC835b00Aa6DAf5852

**Additional context**
While I've had several borrows and added tokens to my stake over time, this is my first time attempting to unstake them since SSS launch in May, so hopefully there wasn't any action I needed to take at some point and missed it. Thank you in advance for the help!

**Comment by hskainth** [comment]
Internal issue 1839 opened for this to investigate.

**Comment by hskainth** [comment]
@mkm703  please try a hard reset of the browser CTRL + SHIFT + R and try this again. This should work.

**Comment by hskainth** [comment]
Closing issue as no response from user in 2 weeks, assume this has been resolved.
