### ISSUE TITLE
Can't access balances of farmed deposits

### ISSUE THREAD

**Issue by jrkiger** [UnFederalReserve/community#106]
In May, I went through the process of adding liquidity to my eRSDL and staked it on the old website in this section...
![image](https://user-images.githubusercontent.com/95455364/144531204-7bfcd675-9818-4202-b216-9355d66db941.png)

I have the tx hash numbers should you need.

Since depositing, actually seeing my deposit in the account has been hit and miss. I use a CoolWallet and have had issues with signing into the site even after hard cache resets and clearing browsing history/cookies/data. 

Most recently, when logging on I can only see the small balance of 2.9 eRSDL still in my wallet and cannot see the deposit I made from May.

I cannot find it anywhere. I have been to the new site, the old site, yet still cannot find my deposit or the rewards from it. The old site doesn't even recognise the small balance, yet the new site does.

This is all I can find on the sites...
![image](https://user-images.githubusercontent.com/95455364/144531564-84aeef6a-2f92-47b9-bd13-605ad7c82acf.png)
![image](https://user-images.githubusercontent.com/95455364/144531588-beb05a2d-8689-4fe0-9cc5-267727915d62.png)

I'm using the ETH chain with my CoolWallet.
I have tried many different browsers as well... Chrome, Firefox, Edge yet the problem persists.

Again, I can see the transaction on the blockchain, but cannot access it... please advise.

**Comment by hskainth** [comment]
@jrkiger do you have coolwallet S or cool wallet pro? Have you checked that the wallet is compatible with the latest version EIP if connecting via metamask as there have been updates since may to metamask.

**Comment by jrkiger** [comment]
I have the Coolwallet's CoolBitX.
I don't use Metamask to connect, I've only used the WalletConnect
functionality.

**Comment by hskainth** [comment]
@jrkiger are you still experiencing this?

**Comment by jrkiger** [comment]
@hskainth Yes, I am. I cannot see any balances beyond the 2.9 eRSDL.

**Comment by hskainth** [comment]
@jrkiger if you cannot also see this on https://lending.unfederalreserve.com/ also please provide wallet address and we can look into this.

**Comment by jrkiger** [comment]
@hskainth I cannot see it there either. 
the wallet address is 0x66D445E41394418Fda317C805F38648f1f0EEAB6

**Comment by hskainth** [comment]
@jrkiger one final check please, could you let me know if you can see them on this link -

https://stake-old.unfederalreserve.com/

**Comment by jrkiger** [comment]
@hskainth I cannot see them on that link either

**Comment by hskainth** [comment]
Internal issue 1905 raised to investigate this.

**Comment by hskainth** [comment]
@jrkiger From the screenshots it shows as locked which means you need to unlock the wallet. Try doing this directly on https://stake-old.unfederalreserve.com/farms/eRSDL-ETH%20UNI-V2%20LP

Alternatively, you can withdraw using etherscan -https://etherscan.io/address/0xf8377270af0c864d2b3bab73bb16c65b05767549#writeContract
12.withdraw
_pid = 13
_amount = 547720098494149442369

**Comment by jrkiger** [comment]
@hskainth That is one of the problems. I have 'unlocked' the wallet, but it shows this every time. 

I've never withdrawn using etherscan...
How do I know how much I am withdrawing? I don't know how much I have as a balance from all of the rewards and farming over the last 8 months.
Where is my wallet address to show that it is being withdrawn into my wallet?

**Comment by hskainth** [comment]
@jrkiger 

https://etherscan.io/address/0xf8377270af0c864d2b3bab73bb16c65b05767549#readContract
14. userInfo
pid = 13
addr = 0x66D445E41394418Fda317C805F38648f1f0EEAB6

It will return 2 values, first (amount) is what needs to be entered to the write function.

This will be withdrawn to the transaction sender.

**Comment by jrkiger** [comment]
@hskainth 
I'm sorry for all of the questions, but thank you for your patience :) 

Is the first (amount) my initial deposit?
What is the second (rewardDebt) number for? 

Now that I have that first (amount) number, is it just for my knowledge or do I go back to the 'WRITE' tab and use this to withdraw? 

What was the 547720098494149442369 amount you sent to me before?

**Comment by hskainth** [comment]
@jrkiger 

I believe the second number is how much ersdl rewards will be received upon withdrawal. The 547720098494149442369 was just an example, please disregard.

Correct that needs to be entered in to the write function.

**Comment by jrkiger** [comment]
@hskainth so when I withdraw, do I also need to withdraw the ersdl rewards as a separate transaction? which should i do first?

**Comment by jrkiger** [comment]
@hskainth 
Right oh. I have been able to withdraw everything. Many thanks for your help. You can close this ticket number.

**Comment by hskainth** [comment]
Closing issue as fixed.
