### ISSUE TITLE
Center-align/justify the content in the 'Partners and Affiliates' section on the landing page.

### ISSUE THREAD

**Issue by JackTeague** [UnFederalReserve/community#107]
This is a minor design suggestion for changing the layout of the content in the 'Partners and Affiliates' section on the landing page.
It makes more sense and is a lot more readable to center align/justify the subheadings (Class ID 'partner-item__title') and the partner logos (Class ID 'partner-item__logos').

Here is what it looks like at the moment:
![image](https://user-images.githubusercontent.com/80437836/146312974-cf85f914-8a8e-4bc1-9601-bd5f9d46acca.png)
![image](https://user-images.githubusercontent.com/80437836/146313682-f29e0ca4-00bc-4078-813c-d49b8dd1a4b7.png)

and this is what it would look like after:
![image](https://user-images.githubusercontent.com/80437836/146313041-eb21f39b-c3e3-4fcb-bf87-9143c2577a2e.png)
![image](https://user-images.githubusercontent.com/80437836/146313650-00bb6289-58cd-4802-8d5e-1847ab04a76a.png)

This elevates the design even more so when cycling through the different responsive ranges (Tablet & Mobile).
The change will also increase the user experience by allowing viewers to read this content more efficiently when scrolling down through the sections by not having to move from | center - left - center | but instead | center - center - center |.

**Comment by hskainth** [comment]
@JackTeague thanks for the suggestion we will forward your feedback on to the design team.
