### ISSUE TITLE
My account started liquidating while being round 80%

### ISSUE THREAD

**Issue by nebreg1709** [UnFederalReserve/community#108]
On january 5th i noticed that my lending percentage (borrow) on unfed was nearing the 90%. Of course i don't want that so i payed 5K off and got my borrow percentage back to around 80%. So i thought it was all good.

The next day, when i logged in on unfed, i noticed that my balance of almost 1,1 mln tokens (legacy ersdl because i was leveraged i could not unstake/stake again) was down to about 600.000 tokens and that ersdl had payed of 20K of my borrowings. Ofc also affecting my borrow percentage again. But i was looking into forums and posted in discord (which initially just got me a response like you will be liquidated when the account is at 100% which ofc i understand). The price of ersdl was roughly about the same as the day before (but i had a cushion so i should have been safe)

On january 7th the remaining 600k tokens also got liquidated (while it wasn't at 100%) and that triggered me to contact because what happened on the 6th should not have happened in the first place. I would have never let it get to the point to get fully liquidated yet here i am. If the first event would not have happened the second would not have happened either. So now my position got wrongfully obliterated and i do like to see a solution for that bc despite the recent events i do have faith in ersdl and that you guys will pull it off. 

Benn directed me to report this issue so here i am. 

My wallet is 0xC80071e5f1e8c83e5A2D50F649A5400F512E8A36

**Comment by hskainth** [comment]
Looking into the above will provide update once complete.

**Comment by triamazikamno** [comment]
Hi,
This is the liquidation transaction(performed by a 3rd party bot not affiliated with unfed): https://etherscan.io/tx/0xb2442caf53a6670ab69593bb2dede81ca74e027b02f315afee29b93e1a015aec

I've run it through the debugger and I can see that your account had $39893.5217 worth of collateral and $40007.6327 worth of debt at the block 13950081, which corresponds to the rate of 100.28%. Price of ersdl at the same block was at $0.0468

**Comment by hskainth** [comment]
Closing issue as per above clarification.
