### ISSUE TITLE
CSS on elements with white background 

### ISSUE THREAD

**Issue by LearnPolkadot** [UnFederalReserve/community#11]
**Is your feature request related to a problem? Please describe.**
1.	On all screens it is hard to read the light grey font (wallet, supply, borrow).  
2.	My eyes are not drawn to anything (ie what I should be doing on this screens).   

**Describe the solution you'd like**
1.	Change the font color to a darker color on every item that can be interacted with.  If an element, such as the withdrawal tab shown below, is a different entity then it can stay the light color though all other labels highlighted below should stand out.
2.	Add required field elements to have user focus on action area.

![image](https://user-images.githubusercontent.com/71201055/114513429-2a670c80-9c08-11eb-98ad-21cbb2d217de.png)

**Comment by harveerenergy** [comment]
Internal issue #346 raised

**Comment by hskainth** [comment]
This has been implemented, closing issue.

![image](https://user-images.githubusercontent.com/81052004/119355106-c6bb0f00-bc9c-11eb-9fd3-5b683abd5db8.png)
