### ISSUE TITLE
Missing security header: X-Frame-Options

### ISSUE THREAD

**Issue by UnCzechReserve** [UnFederalReserve/community#18]
**URL	Evidence**
https://ledger-stage.unfederalreservetesting.com/	Response headers do not include the HTTP X-Frame-Options security header

**Details**
Risk description:
Because the X-Frame-Options header is not sent by the server, an attacker could embed this website into an iframe of a third party website. By manipulating the display attributes of the iframe, the attacker could trick the user into performing mouse clicks in the application, thus performing activities without user's consent (ex: delete user, subscribe to newsletter, etc). This is called a Clickjacking attack and it is described in detail here:
https://owasp.org/www-community/attacks/Clickjacking

Recommendation:
We recommend you to add the X-Frame-Options HTTP header with the values DENY or SAMEORIGIN to every page that you want to be protected against Clickjacking attacks.

More information about this issue:
https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html

**Comment by harv-singh** [comment]
Internal issue #360 has been raised

**Comment by hskainth** [comment]
Issue #360 verified as implemented and closed internally. Closing issue
