### ISSUE TITLE
Missing security header: X-XSS-Protection

### ISSUE THREAD

**Issue by UnCzechReserve** [UnFederalReserve/community#19]
**URL	Evidence**
https://ledger-stage.unfederalreservetesting.com/	Response headers do not include the HTTP X-XSS-Protection security header

 **Details**
Risk description:
The X-XSS-Protection HTTP header instructs the browser to stop loading web pages when they detect reflected Cross-Site Scripting (XSS) attacks. Lack of this header exposes application users to XSS attacks in case the web application contains such vulnerability.

Recommendation:
We recommend setting the X-XSS-Protection header to `X-XSS-Protection: 1; mode=block`.

More information about this issue:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

**Comment by harv-singh** [comment]
Internal issue #361 has been raised

**Comment by hskainth** [comment]
Issue #361 verified as implemented internally, closing issue.
