### ISSUE TITLE
Missing security header: Referrer-Policy

### ISSUE THREAD

**Issue by UnCzechReserve** [UnFederalReserve/community#20]
**URL	Evidence**
https://ledger-stage.unfederalreservetesting.com/	Response headers do not include the Referrer-Policy HTTP security header
 
**Details**
Risk description:
The Referrer-Policy HTTP header controls how much referrer information the browser will send with each request originated from the current web application.
For instance, if a user visits the web page "http://example.com/pricing/" and it clicks on a link from that page going to e.g. "https://www.google.com", the browser will send to Google the full originating URL in the Referer header, assuming the Referrer-Policy header is not set. The originating URL could be considered sensitive information and it could be used for user tracking.

Recommendation:
The Referrer-Policy header should be configured on the server side to avoid user tracking and inadvertent information leakage. The value no-referrer of this header instructs the browser to omit the Referer header entirely.

Read more:
https://developer.mozilla.org/en-US/docs/Web/Security/Referer_header:_privacy_and_security_concerns

**Comment by harv-singh** [comment]
Internal issue #362 has been raised

**Comment by hskainth** [comment]
Issue #362 verified as implemented internally, closing issue.
