### ISSUE TITLE
Missing security header: X-Content-Type-Options

### ISSUE THREAD

**Issue by UnCzechReserve** [UnFederalReserve/community#22]
**URL	Evidence**
https://ledger-stage.unfederalreservetesting.com/	Response headers do not include the X-Content-Type-Options HTTP security header

**Details**
Risk description:
The HTTP header `X-Content-Type-Options` is addressed to the Internet Explorer browser and prevents it from reinterpreting the content of a web page (MIME-sniffing) and thus overriding the value of the Content-Type header). Lack of this header could lead to attacks such as Cross-Site Scripting or phishing.

Recommendation:
We recommend setting the X-Content-Type-Options header such as `X-Content-Type-Options: nosniff`.

More information about this issue:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options.

**Comment by harv-singh** [comment]
Internal issue #364 has been raised

**Comment by hskainth** [comment]
Verified internally as implemented, closing issue.
