### ISSUE TITLE
When Adding Collateral

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/community#23]
**Is your feature request related to a problem? Please describe.**
When adding collateral for an asset the name displayed for eRSDL is the long token name. 

![Screenshot 2021-04-14 at 23 02 35](https://user-images.githubusercontent.com/82473057/114786449-0a555b80-9d76-11eb-9239-2c4b31263639.png)

**Describe the solution you'd like**
It would be better if it was the token ticker symbol eRSDL instead. Same applies to the other tokens. It makes it more obvious to the user what asset they have selected.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by harv-singh** [comment]
Internal issue #374 raised

**Comment by hskainth** [comment]
Verified as fixed, closing issue.
