### ISSUE TITLE
Display Rewards Breakdown

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/community#24]
**Is your feature request related to a problem? Please describe.**
The breakdown of rewards earned is not clear.

**Describe the solution you'd like**
It would be a great feature if we could see a breakdown of the rewards earned on the Supply and Borrow side. I'm assuming both rewards are just bundled into the Unclaimed Balance.

![Screenshot 2021-04-14 at 23 26 39](https://user-images.githubusercontent.com/82473057/114788333-2d353f00-9d79-11eb-8fe2-7a277be9ca8f.png)

Also maybe a total rewards received and claimable as Bancor shows.

![Screenshot 2021-04-14 at 23 27 49](https://user-images.githubusercontent.com/82473057/114788370-3c1bf180-9d79-11eb-8690-3db18961127a.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by harv-singh** [comment]
Internal issue #375 raised

**Comment by hskainth** [comment]
This was resolved in a different manner after review by adding the CLAIM balance in the button to avoid any confusion. Closing as implemented see below screenshot.

![image (2)](https://user-images.githubusercontent.com/81052004/123929637-ea9dfe80-d986-11eb-9f5d-32164f790383.png)
