### ISSUE TITLE
Compound Popup Close & Etherscan Link

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/community#25]
**Is your feature request related to a problem? Please describe.**
A suggestion picked up from discord.

Compound has the ability to close the transaction popup.  Compound has a little X in the top right. Also a link to Etherscan for any transaction.

<img width="521" alt="compoundX" src="https://user-images.githubusercontent.com/82473057/114907068-99b04c80-9e12-11eb-8cee-a4df8d049d97.png">

**Describe the solution you'd like**
Consider adding a popup dialog close X and also a link to the transaction on Etherscan.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hskainth** [comment]
This is as per design for transaction pop up modals. Only error modals can be forced to close.

**Comment by ReluctantHodler** [comment]
What about the transaction link to etherscan?

**Comment by hskainth** [comment]
I will raise internally for etherscan link

**Comment by hskainth** [comment]
Internal ticket #356 raised for etherscan link.

**Comment by hskainth** [comment]
@ReluctantHodler  this has been implemented, please close ticket. -

![etherscan1](https://user-images.githubusercontent.com/81052004/119258007-ce58b600-bbbf-11eb-9164-a5653618886d.JPG)
