### ISSUE TITLE
Repaid all borrowed unETH but still shows up as borrowed 0.1

### ISSUE THREAD

**Issue by UnCzechReserve** [UnFederalReserve/community#26]
**Describe the bug**
I borrowed ETH and repaid all (max). But afterwards it still shows I have 0.1 ETH borrowed but i also cant pay it back.

**To Reproduce**
1. borrow unETH (preferably over 80%)
2. pay it back via the max button
3. 0.1 unETH is still borrowed

**Expected behavior**
0.0 unETH would be borrowed. Also not solved after page refresh...

**Screenshots**
![image](https://user-images.githubusercontent.com/82503926/115019111-02ea9b00-9eb9-11eb-859b-69216802f4f3.png)

**Desktop (please complete the following information):**
 - OS: windows pro
 - Browser chrome

**Wallet Version (please complete the following information):**
 - Wallet: Metamask
 - Public Address: 0x5c16c5AE6EEb21637C02B9C87AB54d9AE8C1Fac2

**Comment by ReluctantHodler** [comment]
Have a look at this close ticket, it looks like the same thing I raised #14

**Comment by UnCzechReserve** [comment]
thank you @ReluctantHodler  - i checked and it iss not the same issue. I already paid back and have no way to pay the remaining amount via the UI. I can share my screen if it helps.

there is no way I could re-pay the missing 0.1 unETH. also there was no error in metamask

**Comment by hskainth** [comment]
@UnCzechReserve have you tried manually inputting in value?

**Comment by UnCzechReserve** [comment]
yes @hskainth

**Comment by hskainth** [comment]
@UnCzechReserve  could you please also provide screenshot of supply side as shows you are over 80% of borrow balance from screenshot provided. 
Although complete exit is not possible with ETH it should be able to repay most of 0.1 amount so wondering if you have too much supply or wallet balance tied up as collateral against borrow of WBTC.

**Comment by UnCzechReserve** [comment]
sorry for the late reply. hee we go:

![image](https://user-images.githubusercontent.com/82503926/116036051-581b6f00-a666-11eb-8350-59a16c2b3901.png)

**Comment by UnCzechReserve** [comment]
small update - i was able to remove the 0.02ETH and pay back in 2 transactions (!?) some more ETH. But now its still some 0.0000000000someting in the borrow market. Again its nothing important but definitely some bug somewhere.

**Comment by hskainth** [comment]
@UnCzechReserve have you tried to enter a value manually in excess of max value that comes up as borrow APY is always generating interest
