### ISSUE TITLE
Not enough tokens available on the market

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/community#28]
**Describe the bug**
Tried to borrow the max available YFI showing on the platform and it produced an error.

**To Reproduce**
1. Make sure you have enough liquidity supplier
2. Try to borrow YFI
3. Enter the Available amount

**Expected behavior**
I would expect to be able to borrow what the system is showing as available.

**Screenshots**

![Screenshot 2021-04-16 at 13 08 44](https://user-images.githubusercontent.com/82473057/115022817-d4b78c00-9eb5-11eb-9997-d8b81a39ab47.png)

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0xCa949793838756D06c2f9F273fEa9dD365393AB7

**Additional context**
N/A

**Comment by Jag1899** [comment]
Column Available shows you all available tokens in the market. And when you click max, it sets max of your available tokens(from column in supply market)

**Comment by hskainth** [comment]
the display of this is to 2 decimal point values, the error pop up suggests the true amount passed 0.04 is not sufficient for e.g. 0.04356 ma collateral user can borrow Vs 0.041000 available  and as such not a bug, please close.

**Comment by ReluctantHodler** [comment]
It is a bug as far as I can see. I've tried to borrow 0.04 which it's telling me is available, but then it produces an error message saying 0.04 is not available.

The lack of fidelity in decimal precision seems to cause multiple issues through the app. I'd suggest looking at this generally.

**Comment by hskainth** [comment]
Although error message is still valid and ultimately does not functionally allow user to borrow more than available, looking at adding in enhancement to stop at stage earlier, this issue is related to #29 and same implementation should fix both scenarios.

**Comment by hskainth** [comment]
Internal issue 387 raised for #28 & #29

**Comment by hskainth** [comment]
@ReluctantHodler this has been fixed and verified internally please close.

**Comment by ReluctantHodler** [comment]
Closed as requested
