### ISSUE TITLE
Clicking 80% Limit Link/Button it defaults to more than available

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/community#29]
**Describe the bug**
When you click the 80% Limit Link/Button it defaults to the max you are able to borrow rather than limiting the amount to what is actually available for the asset.

**To Reproduce**
1. Ensure you have more liquidity provided than you need to borrow to available of an asset
2. Attempt to borrow an asset
3. Click 80% Limit link/button
4. See it defaults to the max you can borrow based on your balance rather than limiting it to what's available for the asset

**Expected behavior**
When the available amount for an asset is less than your borrowing power, default to the available amount.

**Screenshots**
![Screenshot 2021-04-16 at 13 12 44](https://user-images.githubusercontent.com/82473057/115023589-e9485400-9eb6-11eb-98e3-3171ee521bf3.png)

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0xCa949793838756D06c2f9F273fEa9dD365393AB7

**Additional context**
N/A

**Comment by hskainth** [comment]
@ReluctantHodler  Could you please also provide screenshot of the supply/All markets.

**Comment by ReluctantHodler** [comment]
@hskainth here you go. Let me know if you need anything else.

![Uploading Screenshot 2021-04-16 at 17.00.19.png…]()

**Comment by Jag1899** [comment]
Thanks @ReluctantHodler , will run it by the dev team

**Comment by Jag1899** [comment]
Not a bug. Column Available shows you all available tokens in the market. And when you click max, it sets max of your available tokens(from column in supply market)

**Comment by ReluctantHodler** [comment]
@Jag1899 I disagree. The default in this instance should be the max available to borrow, not the max in your wallet as it fills the borrow amount with an invalid amount. This would then need to be manually updated by the user to compete the transaction successfully.

You should also display a message saying that the Maximum available to borrow is less than they are able to borrow.

**Comment by hskainth** [comment]
@ReluctantHodler it should not provide max value overall available to borrow for the following reasons -

(A) It does not reflect what the user is able to borrow who will be limited by his collateral holding
(B) Live system this value will be changing real time as multiple users borrow real time so this value is unlikely to remain the same

This should display max value that user can transact at the time based on collateral, looping in  @vladyslav2 could you please confirm?

**Comment by ReluctantHodler** [comment]
I think it's not good practice to populate a value that is going to produce an exception when there is a simple way to address it. As a compromise I'd be happy with you allowing the population of the max a user could borrow dependent on collateral, but a warning message should tell the user there is not enough liquidity to borrow that amount.

**Comment by hskainth** [comment]
@ReluctantHodler  Yes although edge scenario this could possibly occur at the start and I agree we could make it so that if max collateral value exceeds max available user gets notified, or that max value is capped against max available if this exceeds max collateral. 

This would also address issue current functionality with #28  and we could close both with same fix once done.

**Comment by hskainth** [comment]
Internal issue 387 raised for #28 & #29

**Comment by hskainth** [comment]
@ReluctantHodler this has been fixed and verified internally please close.

**Comment by ReluctantHodler** [comment]
Closed as requested
