### ISSUE TITLE
Available & Liquidity not displayed for Borrow Market Assets

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/community#31]
**Is your feature request related to a problem? Please describe.**
When you borrow an asset you are no longer able to see the Available & Liquidity numbers as you can in the Borrow All Markets section. As a borrower I may wish to borrow the same asset, but access to this information is not available.

![Screenshot 2021-04-17 at 22 34 23](https://user-images.githubusercontent.com/82473057/115127366-cfe5fb80-9fcd-11eb-9fb1-f79aa566aad6.png)

**Describe the solution you'd like**
I would like to be able to see the Available balance and Liquidity value for assets I have borrowed so I can make an informed choice should I wish to borrow more of an asset.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by harv-singh** [comment]
Internal enhancement #398 has been raised

**Comment by dpiatti** [comment]
thats correct - i did post the same issue on discord a while back and forgot to create the ticket here afterward.

**Comment by hskainth** [comment]
Enhancement implemented internally, closing as resolved.
