### ISSUE TITLE
Problem repaying borrowed asset

### ISSUE THREAD

**Issue by Jaca2112** [UnFederalReserve/community#32]
**Describe the bug**
Can't disable collateral because it is not possible to repay borrowed asset (borrowed balance is zero).
I will attach video of this problem for better understanding

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version 89.0.4389.90

**Wallet Version (please complete the following information):**
 - Wallet: Metamask
 - Public Address: 0x10F1C3704933CA83B829b578e57B3f620c82Afd5

https://user-images.githubusercontent.com/82778564/115159514-bc04cd00-a093-11eb-84ff-f00d8b8a4f29.mp4

**Comment by hskainth** [comment]
Internal issue 396 already exists for this.

**Comment by hskainth** [comment]
Interest earned/accrued is automatically compounded per block. Completing any transaction (including withdrawal/repayment) requires a certain amount of blocks. While the transaction is being completed, new interest is going to be computed over the course of this operation. In the case of ETH, this is the fraction of the smallest decimal thus so-called “dust” is created. ETH “dust” presents itself only with ETH supply/borrow and is prevalent across other Defi platforms.
