### ISSUE TITLE
Withdrawing fractions of a token

### ISSUE THREAD

**Issue by Jaca2112** [UnFederalReserve/community#33]
**Describe the bug**
I don't know if this is an issue but there is transaction error when trying to withdraw fraction of a token.

Desktop (please complete the following information):

OS: Ubuntu 20.04
Browser: Chrome
Version 89.0.4389.90
Wallet Version (please complete the following information):

Wallet: Metamask
Public Address: 0x10F1C3704933CA83B829b578e57B3f620c82Afd5

https://user-images.githubusercontent.com/82778564/115160959-35ec8480-a09b-11eb-8089-b319255ec85c.mp4

**Comment by hskainth** [comment]
@Jaca2112  Transaction is successfully completed. I have tried to reproduce this and am unable to.  Could you try with a new account?

**Comment by Jaca2112** [comment]
> @Jaca2112 Transaction is successfully completed. I have tried to reproduce this and am unable to. Could you try with a new account?

Yes sir! I will try and send a video in comments.

**Comment by Jaca2112** [comment]
New account tried 2 times 

TX HASH:
0xb72c13029a241966350aed071fb3eef4688a1c6c69ecf7e54bacc120c7b3a368
0x5c91d473d0bb3b4861a44afc8a3819c1febeaefafb9e86c4a340d774ce746e5b


https://user-images.githubusercontent.com/82778564/115394811-7bb46480-a1e3-11eb-8d5a-c51784ae43f7.mp4

**Comment by hskainth** [comment]
@Jaca2112  am able to reproduce this now too, thanks i have raised internal issue 402 for this

**Comment by hskainth** [comment]
Internal issue closed as fixed.
