### ISSUE TITLE
No Max Length on Number Entry

### ISSUE THREAD

**Issue by ReluctantHodler** [UnFederalReserve/community#38]
**Describe the bug**
I was able to enter a very large number of decimal places.

**To Reproduce**
1. Go to the Supply dialog and type in a a number with a lot of decimal places
2. see error

**Expected behavior**
Limit number of decimals that can be entered

**Screenshots**
https://user-images.githubusercontent.com/82473057/115474791-26557300-a236-11eb-8bfc-31d38a549ac6.mov

![Screenshot 2021-04-21 at 00 06 58](https://user-images.githubusercontent.com/82473057/115474836-3f5e2400-a236-11eb-9ba4-fcea1ac3e952.png)

**Desktop (please complete the following information):**
- Mobile/PC : Macbook Pro 
- OS/version : Mac OS Big Sur 11.2.3 (20D91)
- browser/version : Chrome Version 89.0.4389.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
- wallet/version : Metamask v 9.3.0
- Test wallet : 0x9B0Fff2102d23D25F541684c8109EFa7D91EE11c

**Additional context**

**Comment by hskainth** [comment]
Good spot, although user is only allowed to transact up to 14dp i agree entry should also be limited to this. Internal issue 406 raised for this.

**Comment by hskainth** [comment]
This has been implemented internally. Closing issue.
