### ISSUE TITLE
Collateral not displaying on platform 

### ISSUE THREAD

**Issue by lukenathan91** [UnFederalReserve/community#44]
LINK collateral is not showing up on unfederal reserve platform. 

<img width="1204" alt="UNFED" src="https://user-images.githubusercontent.com/34322007/117520112-94bc6400-af9e-11eb-8078-3164cb120351.png">

1. Enable LINK 
2. Use LINK as collateral 
3. Supply max 
4. After confirmed ethereum transactions the LINK collateral will not display on the platform. 

**Expected behavior**
I expected my collateral to be displayed when connecting to my metamask wallet 

**Screenshots**
Here are the screenshots of the ethereum transactions for each stage of the process. 
 
<img width="1194" alt="Enable LINK " src="https://user-images.githubusercontent.com/34322007/117519895-8e79b800-af9d-11eb-92d6-f0d3b01b9843.png">

<img width="1201" alt="Use LINK as collateral" src="https://user-images.githubusercontent.com/34322007/117519907-9afe1080-af9d-11eb-932d-b76e19b8189e.png">

<img width="1174" alt="Supply LINK" src="https://user-images.githubusercontent.com/34322007/117519915-a3eee200-af9d-11eb-9cfe-bbc196fd0807.png">

**Desktop (please complete the following information):**
 - OS: OS Catalina 10.15.7
 - Browser Chrome 
 - Version 90.0.4430.93 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
 - Wallet: Metamask 
 - Public Address: 0xa9E7151216503a19bce4c88c796f864f771bF99C

My unLINK has arrived in the following contract which seems odd. 

<img width="1198" alt="UnLINK?" src="https://user-images.githubusercontent.com/34322007/117520061-532bb900-af9e-11eb-8650-98a3eb89971a.png">

This is the contract that detains my collateral. 

<img width="1191" alt="LINK COLLA" src="https://user-images.githubusercontent.com/34322007/117520548-a0a92580-afa0-11eb-9c59-1e3495395774.png">

**Comment by consta-l** [comment]
Hi @lukenathan91 
Thank you for submitting an issue. 
We’ll get back to you with a response as quickly as possible. Evenings and weekends may take us a little bit longer.

**Comment by lukenathan91** [comment]
Hi @onetwoitsthewu, 

Thanks for your answer, I have gone through the steps but to redeem the transactions would currently cost $450 in gas fees. 

Can you advise on what I should do? 

Thanks, 

Luke

**Comment by hskainth** [comment]
@lukenathan91 please proceed with transaction and provide transaction ID, we will re-imburse the gas

**Comment by hskainth** [comment]
Closing as resolved as no reply from user for over 2 weeks.
