### ISSUE TITLE
Enabled eRSDL cannot be added to supply 

### ISSUE THREAD

**Issue by Village-Bitiot** [UnFederalReserve/community#45]
**Describe the bug**
I have successfully enabled my eRSDL. I have attempted to add them to supply and the tx was successful and the fees paid. The supply balance is still 0 and the net apy is still 0 as well. 

**To Reproduce**

**Expected behavior**
I expected the ersdl to be added to the supply and have the screen change to show this.

**Screenshots**

**Desktop (please complete the following information):**

**Wallet Version (please complete the following information):**
 - Wallet: [e.g. MetaMask, Coinbase]
 - Metamask 
 - Public Address: [e.g. 0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7]
 

**Additional context**
Add any other context about the problem here. I have made two attempts and paid the fees both times and don’t want to keep trying

**Comment by consta-l** [comment]
Hi @Village-Bitiot 
Thank you for submitting an issue. 
We’ll get back to you with a response as quickly as possible. Evenings and weekends may take us a little bit longer.

**Comment by Village-Bitiot** [comment]
Thanks for the reply. I moved it back to metamask. Was taking too long and I also realized the fees were so high that it would have been difficult for me.

**Comment by hskainth** [comment]
closing as non issue
