### ISSUE TITLE
Enabled ersdl tokens added to lending supply is not reflected after transaction completed

### ISSUE THREAD

**Issue by havingfun-maybe** [UnFederalReserve/community#46]
**Describe the bug**
I added 1,107.559701153464777295 eRSDL tokens to the eRSDL supply for lending. After a successful transaction, the lending website does not reflect my addition after reconnecting my wallet. With my wallet connected, the balance shown now is zero. See the attached screenshot. The clear and concise description is the 1,107.559701153464777295 eRSDL tokens were transferred from my wallet but the balance shown on the lending website, with my wallet connected, is zero.

**To Reproduce**
From the ersdl page on the CoinMarketCap website, click the link for the unfederalreserve website.
On the unfederalreserve website, click the link for Lending.
Connect a MetaMask wallet.
On the left section labeled "All Supply Markets", click on the un Ersdl icon to add to the supply.
Follow the exact steps outlined in the video on the Docs page to add to the supply of eRSDL. ** I chose the "Max" icon instead of entering the amount manually.
Immediately following the transaction, the balance was reflected on the lending website. Oddly though, the apy was over a million and I earned 488 rewards in just a few minutes.
After disconnecting my wallet and reconnecting a short while later, this is when the balance of my wallet and rewards showed zero.

**Expected behavior**
I expect that the 1,107.559701153464777295 eRSDL tokens I added to the lending supply will be shown correctly when I connect my wallet instead of showing zero for the balance. I also expect that rewards will be generated as I have added to the lending supply.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 90.0.4430.93

**Wallet Version (please complete the following information):**
 - Wallet: MetaMask
 - Public Address: 0xdca742F81cD1F4fC8b188637b1EA60B37a827d30

**Additional context**
Transaction hash is 0x742ef93d2da77283131db0b710409f853c397468ef92c7a9fd118fb6ac9b3da6

![balance](https://user-images.githubusercontent.com/83849319/117523018-223a8c80-af7c-11eb-90df-9f91aabb84e5.PNG)

**Comment by hskainth** [comment]
@havingfun-maybe  could you please let me know -
(A) Which network are you connected on to in meta mask wallet? This should be Ethereum main net at the top
(B) Could you click on eRSDL token while connected on platform and send me a screenshot of the pop up modal ?

Thanks.

**Comment by havingfun-maybe** [comment]
Hi.
(A) I am connected to the same network as always, Ethereum Mainnet. See the attached file named mm connection.PNG
![mm connection](https://user-images.githubusercontent.com/83849319/117553630-4d72b980-b018-11eb-9887-3a149f88fbde.PNG)

(B) See the attached screenshot named modal.PNG. I think this is what you are asking for.
![modal](https://user-images.githubusercontent.com/83849319/117553797-223c9a00-b019-11eb-9e06-dd027d0a158e.PNG)

(C) I do not understand this comment. If it shows that my balance is zero, how am I supposed to enable as collateral? The step covering collateral was deferred in the video on the Docs webpage, so maybe I'm not fully understanding the steps required. In that video, tokens were enabled, added to the supply, the transactions were confirmed and the webpage was updated with the balance for the supplied tokens shown on the top left. Seemed fairly simple. I followed the same steps but my balance is zero.

**The main concern is the 1100+ tokens that were in my wallet are no longer in my wallet, and the balance on the eRSDL lending platform shows zero. Where are the 1100+ eRSDL tokens that were transferred and confirmed based on the transaction hash?**

(D) I have cleared the cahce and restarted my browser 3 times already. I have re-booted my laptop 2 times already. There is no reason for me to have to do this again.

**Comment by bojo777** [comment]
i have the same problem. My supplied ersdl just vanished. pls tell me if there is already a fix to this. 
https://etherscan.io/address/0x5A587B4cc426eCa578198c4A53506980883A1f1b if someone wants to check.

**Comment by havingfun-maybe** [comment]
Hi, is anyone available to work on identifying/resolving the issue?

**Comment by havingfun-maybe** [comment]
Hi, when is someone going to be able to help me resolve this issue?
Thanks
    On Sunday, May 9, 2021, 07:23:44 AM CDT, bojo777 ***@***.***> wrote:  
 
 


i have the same problem. My supplied ersdl just vanished. pls tell me if there is already a fix to this.
https://etherscan.io/address/0x5A587B4cc426eCa578198c4A53506980883A1f1b if someone wants to check.

**Comment by onetwoitsthewu** [comment]
hmm i see the corresponding amount of uneRSDL in your wallets via etherscan (50:1 uneRSDL:eRSDL ratio). so it does seem that you have successfully deposited your native tokens and have received your unToken "receipts." @bojo777 - i just checked your eth wallet as well and see uneRSDL in there as well.

@vladyslav2 @hskainth - any thoughts on this? same issue as #50 & #56 i think, possibly #44 as well?

**Comment by havingfun-maybe** [comment]
Well, I must be dense-headed, or I am missing something or I did something wrong when initially trying to stake. Please provide me the exact webpage I need to access to see what you are seeing in regards to my balances. When I go to the website now and choose the Stake button, I end up on a different page than when I initially tried to stake. Maybe I made a mistake and chose the wrong button while initially trying to stake, but it seems that I added the tokens on what looks to be the Lending platform. Did the page for staking change since May 7th.  Whether I connect my wallet to the Staking or Lending platform, my balances show zero. See the following screenshots.
![image](https://user-images.githubusercontent.com/83849319/119212647-5e431680-ba7f-11eb-9869-ee239ebdf9a8.png)

![image](https://user-images.githubusercontent.com/83849319/119212681-98acb380-ba7f-11eb-92ce-2154380a64be.png)

![image](https://user-images.githubusercontent.com/83849319/119212723-dd384f00-ba7f-11eb-8e3d-43a5a2b1c1c1.png)

**Comment by vladyslav2** [comment]
@havingfun-maybe 

please do this:

1. open this link
https://etherscan.io/address/0xf908dcd35129fefb01d39685425eca88c3a8a506#writeContract

2. click connect to web3
3. scroll down to 18. redeem
![image](https://user-images.githubusercontent.com/704096/119231077-daffe000-bad3-11eb-9f62-224f273970cf.png)
4. put 5537047207017 in the reemTokens
5. click write

we will reimburse your gas fee

**Comment by vladyslav2** [comment]
@havingfun-maybe https://etherscan.io/tx/0xa70c97c3d7ce06595feeb8c854cd52d64af3e8258dfc430a04d7d2b46253f396 send you eth for gas fee

**Comment by havingfun-maybe** [comment]
hi. i get this error message when i click on Write.

![image](https://user-images.githubusercontent.com/83849319/119232100-89fae680-bae9-11eb-9b6c-df9b071c3e52.png)

**Comment by vladyslav2** [comment]
@havingfun-maybe make sure you are connected to metamask first
![image](https://user-images.githubusercontent.com/704096/119233851-aabe3e80-badf-11eb-8fb6-057198e77bae.png)

=>
![image](https://user-images.githubusercontent.com/704096/119233841-a4c85d80-badf-11eb-9709-2f2c73e1040e.png)

**Comment by havingfun-maybe** [comment]
ok, i did confirm through metamask that i was connected the first time, but it threw the error.
the second time worked, and i now have the 1100+ tokens back in my metamask wallet.

what caused this issue to begin with? if i did something wrong, i would like to know so i don't do it again.

**Comment by hskainth** [comment]
Closing issue as resolved
