### ISSUE TITLE
Cannot stake or repay using Argent

### ISSUE THREAD

**Issue by tone440** [UnFederalReserve/community#47]
**Describe the bug**
I had successfully staked collateral and borrowed multiple times up until about 11:20 CST when I tried to repay a 15k $eRSDL borrow. My wallet is an Argent wallet connected through Walletconnect. Every time I tried to complete the repay transaction, it showed the network connection error. Later I was able to borrow but then tried to stake but was met with the same message. I can borrow and claim rewards but not stake nor repay. 

**To Reproduce**
1. Go to lending.unfederalreserve.com on laptop and connect wallet to Argent via Walletconnect 
2. Click on borrowed ersdl balance (15,000) and tap “Repay”
3. See error “Could not estimate network fee. Please check your network connection and try again” in mobile Argent wallet 
4. Tap “Try Again”
5. See same error message repeatedly popping up

**Expected behavior**
Expected to see a gas fee amount and the ability to approve the transaction. Then 
![7666895D-27F6-4B1D-8B29-7026EABCE0A0](https://user-images.githubusercontent.com/83851030/117523290-a8a39e00-af7d-11eb-9b69-a400a892eee2.png)
would be able to repay and/or stake. 
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15 Catalina
 - Browser chrome
 - Version: latest

**Wallet Version (please complete the following information):**
 - Wallet: Argent (via Walletconnect)
 - Public Address: 0x30281eCffe14a60fca265147d9e1157E4298e779

**Additional context**

**Comment by harv-singh** [comment]
Hi @tone440 can you confirm the wallet address used was: `0x30281eCffe14a60fca265147d9e1157E4298e779`

**Comment by tone440** [comment]
Yes, that is correct

**Comment by tone440** [comment]
All of my funds are stuck and I can’t do anything still. This needs to be fixed

**Comment by tone440** [comment]
> Hi @tone440 can you confirm the wallet address used was: `0x30281eCffe14a60fca265147d9e1157E4298e779`

How long until I can actually access my coins? This is unacceptable

**Comment by ryanmmmmm** [comment]
Any update @harv-singh ? Will ping team in slack

**Comment by Jag1899** [comment]
**Tested using the Argent Wallet from the Android App Store** Functioned as expected,

Created a new Argent wallet

Sent Funds

Request to Supply Eth
![image](https://user-images.githubusercontent.com/36503328/118005336-33034d80-b342-11eb-97c4-ff78cba3400f.png)

![image](https://user-images.githubusercontent.com/36503328/118005447-4f06ef00-b342-11eb-851a-5498abb50640.png)

![image](https://user-images.githubusercontent.com/36503328/118005479-54fcd000-b342-11eb-8f30-7b127f7b7886.png)






Transaction complete
![image](https://user-images.githubusercontent.com/36503328/118005510-5c23de00-b342-11eb-8e2e-f200f806b93b.png)

App Dashboard
![image](https://user-images.githubusercontent.com/36503328/118005593-6b0a9080-b342-11eb-8d2f-e168cf85b570.png)


Borrowed eRSDL - app approval 
![image](https://user-images.githubusercontent.com/36503328/118008600-22a0a200-b345-11eb-8a5f-585ce1e7e4a9.png)

eRSDL tokens brought: 
![image](https://user-images.githubusercontent.com/36503328/118008699-3a782600-b345-11eb-8afd-61950f55e4b8.png)

eRSDL repay - no enough eth error in wallet: 
![image](https://user-images.githubusercontent.com/36503328/118008788-54196d80-b345-11eb-9704-fc960f4c1711.png)

**Comment by tone440** [comment]
I am still getting the same error. I am using an iPhone not Android. Tried restarting the phone and reinstalling the Argent app. Same issue

**Comment by harv-singh** [comment]
Tested using the Argent Wallet from the App store on IOS Apple device - Functioned as expected. Tested using wallet address: `0x5AB10BC4be7f07e2fD537b87BEb496352C54F448` Managed to stake and borrow then repay some of the ersdl as can be seen:  

![Screenshot 2021-05-12 at 17 40 54](https://user-images.githubusercontent.com/44998024/118012976-8c22af80-b349-11eb-949c-234b40c6564d.png)
![Screenshot 2021-05-12 at 17 40 59](https://user-images.githubusercontent.com/44998024/118012980-8cbb4600-b349-11eb-99c8-741250bb53a1.png)
![Screenshot 2021-05-12 at 17 41 10](https://user-images.githubusercontent.com/44998024/118012984-8cbb4600-b349-11eb-93b0-0995075f2f9d.png)
![Screenshot 2021-05-12 at 17 41 14](https://user-images.githubusercontent.com/44998024/118012985-8cbb4600-b349-11eb-961f-f42031a244c5.png)
![Screenshot 2021-05-12 at 17 42 54](https://user-images.githubusercontent.com/44998024/118012987-8d53dc80-b349-11eb-8fc1-5af22e636eae.png)


This sounds like the issue _may be related with_ the wallet provider. Can you please reach out to them?

**Comment by tone440** [comment]
![0420D2F7-3E37-4363-BA0B-1EED8CFB792A](https://user-images.githubusercontent.com/83851030/118056521-b8412f00-b34f-11eb-8029-4e6c323c1a87.jpeg)

**Comment by tone440** [comment]
This is from the Argent co founder.

**Comment by vladyslav2** [comment]
@tone440 our contract is open source and its been working with all other wallets and been tested many many times by our team and compound team
you can check [security audits](https://lending-docs.unfederalreserve.com/docs/security/) of the contract and [source code](https://github.com/UnFederalReserve/unfederalreserve-protocol) by yourself, or anyone else can do this.

Regarding your problem, any way you can export the private key from Argent wallet and I'll write down instructions for you on what to do next/how to do supply/borrow?

Also, did lose something cause of the liquidation/erdsl price dip? I'll be happy to discuss compensation if that happens cause of some technical problems

**Comment by vladyslav2** [comment]
@tone440 last but not least, if you have a direct connection with Argent co-founder we will be happy to jump on the call with him to discuss a problem

**Comment by tone440** [comment]
![Uploading B384225E-EFEB-4B84-9F82-CEB5B3BEA0D4.png…]()

**Comment by tone440** [comment]
![C6F88EE2-06ED-43DD-8A2E-060199C2E215](https://user-images.githubusercontent.com/83851030/118122716-d98a3580-b3b8-11eb-8869-d45e21931177.png)

**Comment by vladyslav2** [comment]
@tone440

1. Please get a private key for your wallet from that app and import that private key to the metamask or any other wallet. Make sure to own a private key for your wallet.
2. Once you will do this I'll navigate you on how to get your coins back with a direct smart contract
3. plus I'm pretty sure everything will work for you if you will use just metamask

**Comment by tone440** [comment]
Thank you. 
On Telegram, Argent co founder is @itamarl
He said to contact him to work on this. 
I looked into exporting the private key but the Argent website says it is stored and encrypted on my phone so I’m not sure if that’s possible. 

Yes I have lost currently aver 56k ersdl because of the price dip and inability to repay or stake. I am at 100% borrow limit now and imagine more will be liquidated.

**Comment by tone440** [comment]
![Uploading 41232027-283E-417C-B1CE-4A8A9EEF53F5.jpeg…]()

**Comment by tone440** [comment]
![Uploading 78D952B7-2ED6-4565-854F-EE678529B73D.jpeg…]()

**Comment by tone440** [comment]
![Uploading 80F89E14-7712-43F2-98F8-75FD7A9CF4BD.jpeg…]()

**Comment by tone440** [comment]
Not sure if the above picture is loading having issues getting it to upload on my end but the images of conversation with argent. They said their wallet is a smart contract wallet so they don’t have private key. There’s suspicion is that you were somehow blocking the smart contract on your end.

**Comment by itamarl** [comment]
Thanks @vladyslav2  so it's seems there is no intrinsic incompatibility. The message @tone440 sees is when we do a gas estimate and detect the transaction would fail. So for some reasons the dapp generates a transaction that would fail, could be for example not enough tokens to repay what they are trying to repay, etc... we'll try to further investigate with @tone440

**Comment by itamarl** [comment]
@harv-singh @vladyslav2 so it seems there is a bug in the dapp, it doesn't check if the wallet has sufficient erc20 allowance.
@tone440 was trying to repay 5800 ersdl but only had a 800 ersdl allowance so the dapp should require to make an erc20 approval first.

**Comment by tone440** [comment]
Please let me know the next steps @harv-singh @vladyslav2 as I have now been fully liquidated of my eRSDL

**Comment by tone440** [comment]
I’m still at 100% and will get further liquidated of my other assets if I can’t repay or stake. Can this be fixed quickly please. Also, I look forward to hearing about compensation because I have now lost 70k ersdl

**Comment by vladyslav2** [comment]
@itamarl [contacts](https://github.com/UnFederalReserve/unfederalreserve-protocol) been verified by at least 5 different audit companies and its compound contracts, we haven't done anything custom to them. The compound does have an unusual way to report for problems, and audit companies mention that but we won't want to change some core principles of the compound work. At least this will require us to pass new audits which are timely and expensive.
Plus, in standard workflows, approval and repay are two different functions. If the user approved to work with 800 coins only its adequate behavior to throw an error if the user trying to operate with a bigger amount

@tone440 if you can get your keys somehow, I'll be more than happy to show you what to do and how to fix your problem.
Personally, I have never used Argent wallet before and don't know how it handles smart contract call. But it looks like @itamarl has found the issue, you need to call the approval function to set up a bigger limit for eRDSL tokens, and seems like he can navigate you on what exactly needs to be done to do this

**Comment by itamarl** [comment]
@vladyslav2 I'm not sure why you are talking about audits. It's not related to smart contracts.
It's a bug in the web front-end. Your app doesn't check if the wallet has sufficient erc20 approval and so doesn't prompt for a new approval. Not a contract issue here, should be straightforward for you to fix.

**Comment by tone440** [comment]
Can you explain how I was able to stake 408 LINK but now can only supply 1.81 LINK as the maximum? I never had an approval for 1.81 LINK

**Comment by tone440** [comment]
Is this being resolved currently? @vladyslav2 @harv-singh

**Comment by tone440** [comment]
More if my assets have been liquidated on the platform. Can you please follow up here?

**Comment by tone440** [comment]
@vladyslav2 It appears the bug may have been fixed?? I was able to repay some ersdl for the first time today. Please confirm. Also would like to discuss compensation for the over 70k ersdl that I lost due to this technical issue.

**Comment by vladyslav2** [comment]
@itamarl 
> I'm not sure why you are talking about audits. It's not related to smart contracts.
> It's a bug in the web front-end. Your app doesn't check if the wallet has sufficient erc20 approval and so doesn't prompt for a new approval. 

Now that made sense. You mention that we are blocking smart contract transactions in your tweet so that's why I talked about smart contracts.

@tone440 @itamarl Guys I'll be very transparent I don't want to do any finger-pointing, so I'll write down clear facts:

We update the codebase to check the limits before every repayment operation.
However it's very concerning that tone440 was able to supply and wasn't able to repay, cause we set up limits on supply operations and it's not possible to supply without a limit. So something or someone updates a limit after supply operation.
As far as I understood argent wallet has some `daily transfer limit` functionality but I'm just trying to find a logical explanation why the limit was updated after.

**Comment by vladyslav2** [comment]
@tone440, and there are still some open questions for you:
- I guess you did not know that it's not possible to export private keys, cause we would help you right away if you would have your keys with you?
- I can see your limit for the eRDSL set up to [786048550000000000](https://etherscan.io/address/0x5218e472cfcfe0b64a064f055b43b4cdc9efd3a6#readContract)
![image](https://user-images.githubusercontent.com/704096/118997459-888cbb00-b93d-11eb-9928-ad267342bcfb.png)
why? by default it should be way bigger, did you change that intentionally, or someone else updated default limits for you?
- if you had an erdsl to repay, why didn't you supply more erdsl to prevent liquidation even? 
- `0x30281eCffe14a60fca265147d9e1157E4298e779` is a smart contract address, so we cannot see your transactions there (at least I don't see staking transaction) can you double-check that its really your address?

**Comment by itamarl** [comment]
@vladyslav2
- re blocking smart contracts that was a question / hypothesis, we know now that wasn't an issue
- Argent doesn't have any more a daily transfer limit, so it's unrelated to that
- The app will ask users to set the erc20 allowance to what they want to use, as setting the infinite allowance is a **terrible** security practice, this exposes users to massive losses. So @tone440 must have set the erc20 allowance to what he needed initially
- Then when he came back to repay the loan, the remaining erc20 allowance wasn't sufficient to repay and the dapp failed to check the allowance

**Comment by tone440** [comment]
@vladyslav2 

Thank you for your response. 

No, I was not aware that I could not export private keys until trying when you had asked me, which was 6 days into the issue and about 60k had already been liquidated. @itamarl had replied and I thought you might respond to what he was saying. I tried to get a response for several days but didn’t hear back so I wasn’t sure what to do. I am not a developer. Just a user trying to use the dapp and it was not working. 

I don’t know why the limit is set as it is. The only  actions I performed with ersdl were staking about 70k and borrowing 15k. I also borrowed and supplied a few other assets and was around  60% of the limit.  
As I originally stated in the first post, the following day I was unable to stake/supply anything else. This is when I immediately reached out to Ryan because I kept trying to supply more or repay as the limit increased and ultimately liquidated.  

That address is correct and is the only address I used to interact with the dapp
0x30281eCffe14a60fca265147d9e1157E4298e779

**Comment by vladyslav2** [comment]
@itamarl 
> The app will ask users to set the erc20 allowance to what they want to use, as setting an infinite allowance is a terrible security practice, this exposes users to massive losses. So @tone440 must have set the erc20 allowance to what he needed initially

Lets agrees on keeping our own opinion to our self. Cause currently that exactly what has happen user lost his coins cause of incorrect allowance settings. And his settings is was way below what he has supplied.

> Then when he came back to repay the loan, the remaining erc20 allowance wasn't sufficient to repay and the dapp failed to check the allowance and request a higher one
According to the @tone440 he had problems with paying back even lower amount than he supplied

@itamarl @tone440 how can we check his transactions and actually see funds movement? 
`0x30281eCffe14a60fca265147d9e1157E4298e779` its a smart contract and not his direct address

**Comment by itamarl** [comment]
@vladyslav2 I don’t think it’s an opinion, just a fact around poor security practices and many dapps are moving away from this. Users are obviously free to decide to go for a very large allowance if they wish. Tone440 did not loose money because of his allowance but simply because of a bug in the front end. I’m not sure what we are debating here, you have fixed that bug now which is great so it’s pretty obvious what was the cause.

Once we figured out it could be allowance related we asked @tone440 59 try with a very small amount and it worked. So this is the bug, I’m not sure what we are debating here.

**Comment by vladyslav2** [comment]
@itamarl well, i'm not debating, i'm just trying to clear what has happen:
- based on our answers, I assume Argent wallet updated default values for the allowance 
- cause of that user was not able to pay back his debt (I agree we should also have some check on the repay but usually people who are updating default values knows what they are doing)
- cause of the way Argent works user was not able to export private keys, so it wasn't possible to help him quickly
- by the time we added check for the repay function user lost his money.

Can you please show us transactions used made/or explain how we can verify those transactions? cause currently all we can see is some smart contract address
 
BTW take a look on uniswap/compound/etc they all set max allowance by default
PS once again i'm not blaming anyone, we just want to get clear facts

**Comment by itamarl** [comment]
@vladyslav2 agree no worry, let’s focus on making sure it doesn’t happen again.

- users can enter whatever value they want yes
- I don’t see why export a private key would help. There is no easy way in Metamask to change an allowance. It’s always the dapp requesting it.

I don’t know what trx there is to check, no trx was made since the user was not able to change the allowance. The app detects if a trx will fail so the repayment trx couldn’t be sent as there wasn’t enough allowance.

Correct for Compound but Uniswap changed that a long time ago already. 

![70A54AFE-A368-45DC-B505-B2C82C3BC276](https://user-images.githubusercontent.com/38685/119021238-1943b500-b997-11eb-9965-bc70e4b966b1.png)

**Comment by vladyslav2** [comment]
@itamarl 
> I don’t see why export a private key would help. There is no easy way in Metamask to change an allowance. It’s always the dapp requesting it.


I'm trying to find transactions to `0x3105D328c66d8d55092358cF595d54608178E9B5` from `0x30281eCffe14a60fca265147d9e1157E4298e779` (user wallet)

@tone440 telling he supplied and lost 70k but his current allowance is 0.78 eRDSL
![image](https://user-images.githubusercontent.com/704096/119129722-24750000-b9ec-11eb-95f6-dc2f046a9aec.png)

so it does make sense - he was able to supply ~786048550000000000 + 00000 but his limit is just `786048550000000000`?

@itamarl so we are trying to find transactions to `0x3105D328c66d8d55092358cF595d54608178E9B5` or to `0x5218e472cfcfe0b64a064f055b43b4cdc9efd3a6` to inspect them. Can you explain how to do find for users or argent wallet?

**Comment by itamarl** [comment]
@tone440 should be able to find these transactions in the Argent app then long press on the hash to copy it

alternatively if you look at their wallet in Etherscan you should be able to find the ersdl transfer in the erc20 tab

not sure what part is confusing regarding his allowance? Im assuming he had a larger allowance but used most of it for the initial supply

**Comment by tone440** [comment]
Is this what you’re looking for 
https://etherscan.io/tx/0xb712c942e4820375de9bf27a33471c421410f15dd5f4a5a34f4fb4ea4fe2fbee?__cf_chl_captcha_tk__=29bb1a06235631357253b3efcd6b10f9e13121d3-1621599323-0-AdVd1djyEDvFZLZMUfRX5A64vtejZW6TdNQQg8QuHfKdh1dkMZIxDR7Y53EGPM-t5eo_sJdCGsRWbmsbhEX97EsgLBcrwPqAnZIR22hPyv9TRN2U2GeEGqM2b2j0aBRKAg6Xsa5idvOrDTGHto2GZat4VMk5P3PlzixYyP_Gq-noQLGRYlEhSJ9r6QIp1BcUEE_rjTfaSPtgY5GA9zuQFqJAwYGB_f7pUmWwxN4xI6ofeVohM3MdjuvSwQb8MYm4MevW2x4u14wGc8ZWNqHg8W1kFy5OPmaMiBDEbki3zDuP0w_v6Q_3il4MAkmm6a_fNIcKqLLL5O8dvF1ipLDhureG_UjIz65603lzPahXidt-bM4X0FnVyFmhpR0wtz43_pXqkjA0qXOrxfbnn5NilY_1Zz57Qu7qXHUZT2QefuMx1XXDqWYkZqa9-YIKdU-3JKLncLA3BcEe3INm_pQTGMvQc2jy-2lGMvKuXVq-Iu__vTNrz4NTEv9lZXfdulp-YUE4dCxGnEm6uawo3YqYUwOPv2ytGm8eqRkCcfZRexWJcbDbYGIs2T03qvn9pIfxef_MKoQZ16ehGBPXG_rBitgcoZuOB-GU8EbG6m-ISL4ZgeVPcaH35LmvcV9c2A0Ya2y1R2O1Ti12se5uLGXbRvsk30HMKWTM16mMxiY7rlrC2w6etbF4rkbYppVu10o0lV_WhNx1XTAIzPbNoVJH0ydvycwT-Ew_E-kbYagkojR50nNrzx9VeiHwdM-szitYzg

**Comment by tone440** [comment]
@vladyslav2 Can you please update on this?

**Comment by vladyslav2** [comment]
@itamarl how does argent controls users eth addresses?
in transaction provided by @tone440 has different eth address

Does argent acts as a proxy? or does argent provides stack of the addresses to the user?

**Comment by itamarl** [comment]
@vladyslav2 it’s a smart contract wallet (like a multisig) so it uses meta-trx. So trx.origin is our relayer and msg.sender is the user

**Comment by tone440** [comment]
@vladyslav2 Can you tell me how long will this take? Do you need help from me to find the transactions?

**Comment by tone440** [comment]
@vladyslav2 @harv-singh @ryanmmmmm 
I was told by Sam that this is requiring “additional time to vet and investigate the circumstances as both parties were involved”. 
can you please explain this? How was @itamarl Argent “involved”? 
It seems the bug on your dapp was found and fixed. And it would seem you’ve had ample time to investigate. Please respond - I have not heard anything since May 24.

**Comment by HKrieger55** [comment]
I appreciate everyone's effort trying to resolve this issue. Everything looks documented.  Any further investigation, might be considered tampering at this point, so let's hold off on anything further.  Thanks for the hard work and for trying to do the right thing.

**Comment by HKrieger55** [comment]
@ryanmmmmm you are going to handle direct communication with Tom Ace. Have a good night.

**Comment by ryanmmmmm** [comment]
this can be closed..  a non standard bounty offered to person who submitted issue..
