### ISSUE TITLE
Claiming rewards does not work

### ISSUE THREAD

**Issue by nebreg1709** [UnFederalReserve/community#49]
W**Describe the bug**
I have rewards which i wanted to claim. When i claimed i used the fast gas option and max gas fees and clicked on claim. Nothing happens. I checked my eth wallet to see wether a transaction is there but no transaction from ersdl. Wether i’d use high or low gas, the transaction should always popup in my eth but there is something buggy there.

**To Reproduce**
Just go to claiming rewards. Select the fast option at gas fees and click claim

**Expected behavior
i expected that an eth transaction would be triggered and after the eth transaction would succeed i would be done (but there is no eth transaction popping up). 

the good thing is nothing happens at all. So i am not loosing gas. The bad thing if this problem persists is that ppl will start to panic bc they cannot do anything with rewards. And then they are going to want to withdraw funds and if that does not work either big problem. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Version: 90.0.4430.93

**Wallet Version (please complete the following information):**
 - Wallet: metamask
 - Public address: 0xC80071e5f1e8c83e5A2D50F649A5400F512E8A36

**Additional context**

**Comment by harv-singh** [comment]
Hi @nebreg1709 i see the claim rewards has occured on your wallet address: `0xC80071e5f1e8c83e5A2D50F649A5400F512E8A36` can you confirm this is still an issue please?

**Comment by nebreg1709** [comment]
Hello Harv-singh, i had quite a lot of ppl also having stuck transactions but i can confirm (just checked) that the issue resolved, took a few hours. You are right on the wallet address, but there was a massive queue before my tx growing and growing. I wasn't too worried, but i think something got stuck or temp stopped functioning. So thanks for your reply, issue can be closed for me, but what was behind the issue should be of interest to unfed i think, bc something wasn't going smooth. By the way, good job for the entire team, launched exactly what unfed said so congrats.

**Comment by harv-singh** [comment]
Great to hear and thanks for the insight, you may close this issue.
