### ISSUE TITLE
Supplied ersdl not displaying on platform

### ISSUE THREAD

**Issue by bojo777** [UnFederalReserve/community#50]
**Describe the bug**
hey, my supplied ersdl on Unfederalreserve lending ist not anymore there. you can see here that i supplied 612 ersdl. https://etherscan.io/tx/0x23e0bf221649ea8d47af54928187c33db04621138b9c368374f568850f4e79a2. After claiming my rewards all my ersdl that was supplied was gone and my rewards aswell. claiming rewards didnt give me any reward. I only paid for gas fees and lost eth. 

**To Reproduce**
1. press button to claim rewards
2. accept gas fees for transaction (visible on etherscan 0x5A587B4cc426eCa578198c4A53506980883A1f1b wallet)
3. reloaded my screen to see if rewards landed in my Metamask wallet.
4. supplied ersdl was 0 instead of 612ersdl. rewards 0.

**Expected behavior**
i dont mind not getting my rewards from supplying but i sure want my supplied ersdl.

**Screenshots**
![etherscanWallet](https://user-images.githubusercontent.com/83883683/117551093-3649c100-b044-11eb-84a7-08895dc39db2.PNG)
![lendingConnectedMM](https://user-images.githubusercontent.com/83883683/117551121-58434380-b044-11eb-9449-5627f30f8fc2.PNG)
![ersdlsupply](https://user-images.githubusercontent.com/83883683/117551144-8032a700-b044-11eb-9d52-1ae8f2403b26.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : chrome
 - Version Version 90.0.4430.93

**Wallet Version (please complete the following information):**
 - Wallet:  MetaMask
 - Public Address: [0x5A587B4cc426eCa578198c4A53506980883A1f1b]

**Additional context**

**Comment by bojo777** [comment]
> @bojo777 can you reply if still have an issue?
> From the contract perspective we can see your erdsl are supplied

Hey vlad thanks for your response.
Yes from my perspective i have still the issue. On the lending unferderalreserve site my supply still shows 0 ersdl supplied.

**Comment by bojo777** [comment]
I have tried disconnecting and reconnecting my Metamask wallet.
deleting my chrome cache history.

**Comment by vladyslav2** [comment]
@bojo777 
can you:
1. open this link:
https://etherscan.io/address/0xf908dcd35129fefb01d39685425eca88c3a8a506#writeContract and click 
![image](https://user-images.githubusercontent.com/704096/117949627-fd973980-b31a-11eb-8acc-c5a468d4776a.png) connect to web3
2. find redeem function and enter 3069583468552 (amount of the uneRDSL tokens you have)
![image](https://user-images.githubusercontent.com/704096/117949819-2f100500-b31b-11eb-8284-9c667224198e.png)
3. Click write and confirm your transaction in metamask
4. Once transaction processed you will get back your 612 erdsl tokens

**Comment by bojo777** [comment]
i tried doing that but the gas fees are just way to high right now. 180+$ to accept my coins is too much :(

**Comment by vladyslav2** [comment]
@bojo777 make sense, lets wait
if you won't be able to recover them we will compensate those tokens for you

**Comment by bojo777** [comment]
@vladyslav2 hey, i am really watching the gas price closely but i am just not able to pay the fees anymore. If i get my ersdl back(compensated), will it be sent to my wallet or already supplied like before? Because if i get it in my wallet again then i would need to pay transaction fees again to supply it.(because i would like my ersdl supplied rather than in my wallet). 
I really like this project but through all this process of getting ersdl and supplying i have lost alot of my eth. I am not the only one in this so i cant really complain. 
I want to thank you for helping me in with this issue.

**Comment by vladyslav2** [comment]
@bojo777 we will pay you for the gas fee cause it looks like it was our fault
should we send some eth to 0x5A587B4cc426eCa578198c4A53506980883A1f1b ?

**Comment by bojo777** [comment]
@vladyslav2 Hey, i just tried to claim the 612 ersdl like written above and the gas fees look ok again so i tried it.
https://etherscan.io/tx/0x8b4b8605e7a8c1eb9ae869860f746a01ec4c5d631d23619f56c573141b51a30e
we'll see if it works

**Comment by vladyslav2** [comment]
@bojo777 sent you some eth as reimbursement for gas fee https://etherscan.io/tx/0x8e3368f250e59b2bce258e08606f58db66cccee07b33c097f025a64bf7702d3f

**Comment by hskainth** [comment]
@bojo777 please confirm this has been resolved and issue can be closed.

**Comment by hskainth** [comment]
Closing as resolved as no response for over 2 weeks from user.
