### ISSUE TITLE
Supply Balance is Zero After Lending 

### ISSUE THREAD

**Issue by AvacadoIceCream** [UnFederalReserve/community#53]
On Thursday, I supplied some ersdl tokens as a lender. It showed them on my supply balance. I'm using metamask on my desktop.

Today, I went to check the balance and it's not showing anything in supply or rewards:

![image](https://user-images.githubusercontent.com/83888574/117555519-ecee7700-b02d-11eb-926c-5baefa77604c.png)

I didn't borrow anything, just lending.

On etherscan, I saw that my wallet has received un-ersdl as part of the staking. 

However, I'm still not seeing anything as part of the supply balance or rewards.

Metamask Wallet address:

0xd3972c38BC52F7642415066E879083772E099A06

**Comment by vladyslav2** [comment]
@AvacadoIceCream your erdsl is at supply and I can see two possible reasons why it has happened:
- can you make sure you enter metamask password after you open the website? If you haven't use metamask for a while it will ask to enter a password from your wallet
- can you make sure you open the website using the correct eth address?

**Comment by AvacadoIceCream** [comment]
> @AvacadoIceCream your erdsl is at supply and I can see two possible reasons why it has happened:
> 
> * can you make sure you enter metamask password after you open the website? If you haven't use metamask for a while it will ask to enter a password from your wallet
> * can you make sure you open the website using the correct eth address?

I only have the one metamask account, so that's not the issue:

![image](https://user-images.githubusercontent.com/83888574/117678353-4fa25880-b17d-11eb-899b-a993309f8947.png)

What's the correct eth address for the website?

**Comment by vladyslav2** [comment]
@AvacadoIceCream I can see you do have uneRDSL tokens on your wallet
https://etherscan.io/address/0xd3972c38BC52F7642415066E879083772E099A06
![image](https://user-images.githubusercontent.com/704096/119127434-2d180700-b9e9-11eb-8cfb-288df2c52f8f.png)


which means you should have your eRDSL tokens undersupply table

does you still have the this problem?

**Comment by AvacadoIceCream** [comment]
No, the lending platform is working for me now. I can see what I've supplied. Looks like the issue has been fixed. Thanks
