### ISSUE TITLE
Transaction timing out when attempting to repay loan balance

### ISSUE THREAD

**Issue by Don-Sonora** [UnFederalReserve/community#54]
**Describe the bug**
The bug centers around the processing of the transaction. After the approval of the transaction fee, the payment begins to process, but does not initiate a transfer. 

**To Reproduce**
1. Click on the borrowed asset in My Borrowings. Switch tab to repay and set value to max. (Have enough to cover interest). Select blue repay button at the bottom. 
2. Metamask transaction fee page opens and I approve the transaction fee.
3. Payment begins to process and shows a loading icon wheel. Wait 5 to 10 minutes. 
4. Payment fails without the ethereum being withdrawn from the metamask wallet. 

**Expected behavior**
The payment to process fluidly without timing out. 

**Screenshots**
Will be supplied if necessary

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Home ]
 - Browser [e.g. Chrome ]
 - Version [e.g. Version 90.0.4430.93 ]

**Wallet Version (please complete the following information):**
 - Wallet: [e.g. MetaMask ]
 - Public Address: [e.g. 0x948E277D0DC9d615e009Ea14aC74a696B3b36a99 ]

**Comment by hskainth** [comment]
@Don-Sonora have you retried, does this still happen for you?

**Comment by Don-Sonora** [comment]
I still have 5 pending transactions in metamask and want to clear the queue before I make another attempt. I have reached out to their support to assist in this matter.

**Comment by Don-Sonora** [comment]
Transaction processed successfully
