### ISSUE TITLE
Ersdl Apy should be higher than Stable Coins

### ISSUE THREAD

**Issue by Fynkployd** [UnFederalReserve/community#55]
Hi, please correct me if i am wrong. Isn’t it unfair that the stable coins are getting much higher APY and it was not even clear prior to launch of staking that stable coins will get rewards for staking. I, being a strong believer and supporter of ersdl bought additional 20k usd worth of ersdl on the very last day before staking so i could stake those ersdl and gain some rewards. However now i realize that i would’ve been way better off if i would’ve just staked those 20k USDT instead of converting them to Ersdl. Besides the value of my USDT is around half of what it was 2 days ago :( . Wasn’t the whole idea of staking to inspire people to buy and stake more Ersdl, and join/support the project?

**Comment by nebreg1709** [comment]
Had to react on this issue (i was checking another issue). I can understand that that is the way you feel and it might seem this way but the way i am looking at it it is not that strange the apy went down on ersdl (besides the fact it was all explained in the articles from unfed). If you compare the amount of staked ersdl versus dai/usdt/usdc there is a massive difference, the amount of staked ersdl surpasses x10 the amount of stable coins and what not so the apy for ersdl is really not that bad given the enormous amount staked. Besides, it is a lending/borrowing part that unfed brought to us and much to follow. For a lending and borrowing platform and putting everything in perspective which you should do too in my humble opinion it is essential to attract every type of capital. If there were less ersdl staked the apy would be higher, it is as simple as that. Actually, giving this reward to so many ersdl staked, i am taking my hat of for the team.
