### ISSUE TITLE
My collateral not showing on reserve lending platform  

### ISSUE THREAD

**Issue by Humbley1984** [UnFederalReserve/community#56]
**I have transferred my Ersdl Tokens from Trust Wallet to the reserve lending platform but it is not showing on the dashboard. I can see through etherscan it has gone through - contract address is: 0x66DBDe5Fc3395a2cF954C5d891577Eb8Da02AA38. I can also see the uneRSDL tokens in my trust wallet. Are there some front-end UI bugs? **

**Enter the reserve lending platform from my desktop, connect to my trust wallet, my supply, and collateral added/earned not showing.**

**I have also transferred tokens from my coinbase wallet and can see the tokens clearly as collateral, I expected the same result when adding tokens from trust wallet. **

**![image](https://user-images.githubusercontent.com/83904927/117648500-305bf900-b186-11eb-8b24-c45a68fdda36.png) an imagine of my uneRSDL tokens in my trust wallet**

**Browser - Chrome**

**Trust Wallet -0x66DBDe5Fc3395a2cF954C5d891577Eb8Da02AA38 **
 

**Additional context**

**Comment by hskainth** [comment]
@Humbley1984  is your correct wallet connected on desktop? could you send me screenshot of lending platform on desktop?

**Comment by Humbley1984** [comment]
> @Humbley1984 is your correct wallet connected on desktop? could you send me screenshot of lending platform on desktop?

![image](https://user-images.githubusercontent.com/83904927/117686074-6a40f580-b1ae-11eb-9200-b1498b136016.png)

**Comment by hskainth** [comment]
@Humbley1984 could you click on eRSDL aswell under "All supply markets" on the left hand side and send me a screenshot of the pop up modal?

**Comment by Humbley1984** [comment]
> @Humbley1984 could you click on eRSDL aswell under "All supply markets" on the left hand side and send me a screenshot of the pop up modal?

![image](https://user-images.githubusercontent.com/83904927/117686778-197dcc80-b1af-11eb-8264-f4603f0381e2.png)

**Comment by Humbley1984** [comment]
> > @Humbley1984 could you click on eRSDL aswell under "All supply markets" on the left hand side and send me a screenshot of the pop up modal?
> 
> ![image](https://user-images.githubusercontent.com/83904927/117686778-197dcc80-b1af-11eb-8264-f4603f0381e2.png)

Any ideas as to what is happening?

**Comment by vladyslav2** [comment]
@Humbley1984 it looks like it was our fault
we can send you gas fees for your transactions in eth or erdsl and I'll follow up with instruction on how to get back your erdsl

**Comment by Humbley1984** [comment]
> @Humbley1984 it looks like it was our fault
> we can send you gas fees for your transactions in eth or erdsl and I'll follow up with instruction on how to get back your erdsl

Hi, that would be great if you can, gas fees in Ersdl will be fine... when can you make this happen?

**Comment by vladyslav2** [comment]
@Humbley1984 

please do this:

1. open this link
https://etherscan.io/address/0xf908dcd35129fefb01d39685425eca88c3a8a506#writeContract

2. click connect to web3
3. scroll down to 18. redeem
![image](https://user-images.githubusercontent.com/704096/119231077-daffe000-bad3-11eb-9f62-224f273970cf.png)
4. put 16594940735317 in the reemTokens. `16594940735317` !!!
5. click write

we [reimbursed](https://etherscan.io/tx/0xce7b452ed46dc94e88ae02ba82699f9f7e14162bd172df6f3b540d90ec14cb6a) your gas fee

**Comment by hskainth** [comment]
Closing issue as resolved, gas fee reimbursed as resolution.
