### ISSUE TITLE
My initial ersdl staking amount decreased significantly. 

### ISSUE THREAD

**Issue by lombarto** [UnFederalReserve/community#57]
I staked (Collateral supply) ERSL on the 6 of May. Now checking my balance and I see that the token amount provided decreased by 12%. This is significant. How is that possible and why? How is that when I provide something it decreased within less then a week by 12%? This is absolutely not user-friendly.

I used Trustwallet.

**Comment by hskainth** [comment]
@lombarto please send your wallet address and screenshot of supply screen as well as your ERSDL pop up modal when you click on token.
