### ISSUE TITLE
Unable to remove supply even once borrowings returned

### ISSUE THREAD

**Issue by haddons** [UnFederalReserve/community#58]
![IMG-20210513-WA0020](https://user-images.githubusercontent.com/84111893/118067168-63e78f00-b3e3-11eb-8ad2-1a4664507313.jpg)
![Uploading 20210513_075327.jpg…]()

Hi,
I can't remove my supplied Eth even after returning my borrowings

Wallet address
0xEDfc3F77cCb6Ca9aFd0F162842a76D85360cf006

![20210513_075246](https://user-images.githubusercontent.com/84111893/118067127-4ca8a180-b3e3-11eb-8d9a-bd9414e34405.jpg)
![Uploading 20210513_075246.jpg…]()

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Wallet Version (please complete the following information):**
 - Wallet: [e.g. MetaMask, Coinbase]
 - Public Address: [e.g. 0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7]

**Additional context**

**Comment by charlesbaby** [comment]
I believe it is because you still have a small amount borrowed. It says .01 eth. This is known as eth dust. I believe this is a bug and there is not much you can do about it until admins fix the problem. Seems like this should happen soon. Let me know if anything works for you and keep an eye on their pages.

**Comment by haddons** [comment]
Hi,
How do I follow up and ensure they clear this "dust"?
Thank you
Haddon



Sent from my Galaxy



-------- Original message --------
From: charlesbaby ***@***.***>
Date: 16/05/2021 09:43 (GMT+10:00)
To: UnFederalReserve/community ***@***.***>
Cc: haddons ***@***.***>, Author ***@***.***>
Subject: Re: [UnFederalReserve/community] Unable to remove supply even once borrowings returned (#58)


I believe it is because you still have a small amount borrowed. It says .01 eth. This is known as eth dust. I believe this is a bug and there is not much you can do about it until admins fix the problem. Seems like this should happen soon. Let me know if anything works for you and keep an eye on their pages.

**Comment by charlesbaby** [comment]
I'm not sure sorry. Alex said they are working on it in the Telegram channel. He advised not to waste gas by trying anymore. How they fix or communicate the fix I don't know. I guess I will keep checking here and the telegram. Would be great if they could put out a statement or pinned notice though.

**Comment by hskainth** [comment]
Interest earned/accrued is automatically compounded per block. Completing any transaction (including withdrawal/repayment) requires a certain amount of blocks. While the transaction is being completed, new interest is going to be computed over the course of this operation. In the case of ETH, this is the fraction of the smallest decimal thus so-called “dust” is created. ETH “dust” presents itself only with ETH supply/borrow and is prevalent across other Defi platforms.
