### ISSUE TITLE
Can not get my assets off the platform because of a borrow repayment bug for eth

### ISSUE THREAD

**Issue by Jarsir** [UnFederalReserve/community#59]
I can not repay eth loan. I have tried 4 times hitting max each time (4 gas payments). I suspect that this is the reason I can not withdraw the majority of my collateral

**Expected behavior**
Click eth, Click Repay, click Max, approve transaction and loan is 100% repaid 

![image](https://user-images.githubusercontent.com/34492157/118081142-cf504300-b388-11eb-90f0-5b2fa6809927.png)

**Comment by Jarsir** [comment]
I also expect to be able to withdraw  all of my collateral except x = 4e-18 / 80%  but it requires me to keep many orders of magnitude more capital on the platform. otherwise it reads insufficient liquidity when I attempt to withdraw. and this is my only borrowed loan.
![image](https://user-images.githubusercontent.com/34492157/118081477-6ae1b380-b389-11eb-91d0-a1b6420275b5.png)

**Comment by bnedick** [comment]
Also have this issue. We should have our gas fees refunded in the form of ersdl for this bug.

**Comment by charlesbaby** [comment]
Also having this problem. I have tried to reach out to admins but have not gotten an answer. If anyone gets one can they reply here? I will do the same if I find a solution!

**Comment by bnedick** [comment]
Will do. Haven't received any help yet.

**Comment by charlesbaby** [comment]
Anyone got an update here?

**Comment by hskainth** [comment]
Interest earned/accrued is automatically compounded per block. Completing any transaction (including withdrawal/repayment) requires a certain amount of blocks. While the transaction is being completed, new interest is going to be computed over the course of this operation. In the case of ETH, this is the fraction of the smallest decimal thus so-called “dust” is created. ETH “dust” presents itself only with ETH supply/borrow and is prevalent across other Defi platforms.
