### ISSUE TITLE
Paid off eRSDL Borrow Balance Twice and it still shows that I owe.

### ISSUE THREAD

**Issue by vt3nyc** [UnFederalReserve/community#60]
Hello,

I went to pay off my eRSDL borrow balance in full and when the transaction was over, it said that I still owed a small amount. I went to pay that small amount, incurring another gas fee and nothing changed.

**To Reproduce**
1. Go to 'My Borrowings'
2. Click on 'eRSDL'
3. Click on 'Repay'
4. Enter repay amount
5. Press Repay
6. Accept Gas Fees
7. Still shows small amount
8.  Click on 'Repay'
9. Enter repay amount
10. 5. Press Repay
11. Accept Gas Fees
12. Still shows small amount

**Expected behavior**
I expected my borrow balance to be paid in full after having done it twice. It still showing as owed.

<img width="505" alt="Shot 1" src="https://user-images.githubusercontent.com/84165158/118214339-8c03dc00-b43d-11eb-8284-acb7c9e20bb9.png">
<img width="516" alt="Shot 2" src="https://user-images.githubusercontent.com/84165158/118214342-8c9c7280-b43d-11eb-8a68-b75673a2abc3.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 89

**Wallet Version (please complete the following information):**
 - Wallet
 - Public Address: [0xB5Bb226f2d36f539210094fb4eA6Fe5df3833c54]

**Additional context**

**Comment by hskainth** [comment]
@vt3nyc just tried this on chrome browser and worked fine for me, i was able to repay 100% -

Have you tried clearing your browse cache and verify your wallet is on ethereum mainnet?

![Repay 4](https://user-images.githubusercontent.com/81052004/118299087-37fa0580-b4d8-11eb-91c8-515c4213a9a5.JPG)
![Repay 3](https://user-images.githubusercontent.com/81052004/118299090-38929c00-b4d8-11eb-84ff-cab84bf1086f.JPG)

**Comment by vt3nyc** [comment]
Hey, 

Thanks for the reply.

I cleared my cache and checked my transaction history and it still shows the balance even though I essentially paid it twice.

**Comment by hskainth** [comment]
Internal issue 532 raised which is similar to as described.

**Comment by vt3nyc** [comment]
<img width="503" alt="Screen Shot 2021-05-16 at 12 20 22 AM" src="https://user-images.githubusercontent.com/84165158/118385407-82fd4100-b5dc-11eb-8c75-5b1ce67335b6.png">

Regardless of how fast I put it, there's always a leftover amount. I'd even put more if it would let me. At this point, not sure what else to do. I'd hate to keep wasting gas for an amount so minuscule but it is tying up the supply side.

**Comment by batinhell** [comment]
@vt3nyc you need to click max button to fully repay your loan.

**Comment by vt3nyc** [comment]
Hello,

@batinhell 
I did that, put fast gas and the balance is still there. 

<img width="515" alt="Screen Shot 2021-05-16 at 12 18 58 PM" src="https://user-images.githubusercontent.com/84165158/118404455-e7ea8280-b640-11eb-99e3-9d54327bb501.png">
