### ISSUE TITLE
Unable to borrow assets without same asset collateral

### ISSUE THREAD

**Issue by cieltan** [UnFederalReserve/community#65]
**Describe the bug**
Multiple users have reported being unable to borrow assets that they do not possess the same collateral for. For example, a user cannot borrow USDT without already supplying USDT.

**To Reproduce**

1. Go to https://lending.unfederalreserve.com/
2. Click on any asset that you do not currently provide as collateral (i.e. I am supplying DAI but I want to loan from USDT)
3. Enter any number amount to borrow when dialog is opened and click submit.
4. UI throws 'execution reverted: market borrow cap reached' message to user.
5. Chrome devtool returns this error response: 
```
{
    "code": -32603,
    "message": "execution reverted: sender must be cToken",
    "data": {
        "originalError": {
            "code": 3,
            "data": "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001573656e646572206d7573742062652063546f6b656e0000000000000000000000",
            "message": "execution reverted: sender must be cToken"
        }
    }
}
```

**Expected behavior**
I am able to successfully borrow assets that I do not own.

**Screenshots**
<img width="1679" alt="Screen Shot 2021-05-14 at 4 50 01 PM" src="https://user-images.githubusercontent.com/40251412/118330097-4abf0b00-b4d5-11eb-955a-4b417955522c.png">
<img width="631" alt="Screen Shot 2021-05-14 at 4 50 48 PM" src="https://user-images.githubusercontent.com/40251412/118330112-4e529200-b4d5-11eb-96f2-23f04b1e51be.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 90.0.4430.93 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
 - Wallet: Metamask
 - Public Address: 0xe17b0e1B433FA922D2DB81C054C40A207B0F9Bcf
 
 No transactions were done, I was simply testing the front-end UI.

**Comment by vladyslav2** [comment]
@cieltan looking

**Comment by vladyslav2** [comment]
@cieltan can you check? you might need to do hard reload (cmd + shift + R on mac or ctrl + shift + R on win)

**Comment by cieltan** [comment]
@vladyslav2 The hard reload seems to have resolve the issue. Thank you.

**Comment by hskainth** [comment]
@LearnPolkadot please close issue as fixed.

**Comment by vladyslav2** [comment]
closed due inactivity
