### ISSUE TITLE
Repaid loan but balance still the same

### ISSUE THREAD

**Issue by AgentGeeJayCee** [UnFederalReserve/community#66]
**Describe the bug
Keep spending gas fees to repay loan but loan stays at same balance

**To Reproduce**
1. Go to borrowings
2. Click on repay loan
3. Press max and repay
4. Put same amount in Argent wallet to repay
5. Confirm gas fee
6. Transaction goes through as completed in wallet and etherscan
7. Go back to unfed platform, loan still showing

**Expected behavior**
Loan to be repaid

**Screenshots**
![image](https://user-images.githubusercontent.com/84189864/118387862-b9f14800-b618-11eb-8811-1841fff685f8.jpeg)
![image](https://user-images.githubusercontent.com/84189864/118387856-b067e000-b618-11eb-8749-4635f271c6a3.png)
**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser safari
 - Version 14.5.1

**Wallet Version (please complete the following information):**
 - Wallet: Argent
 - Public Address: 0xe533361D20Df1c0A575C87493418Bd62c26Bba06

**Additional context**

**Comment by AgentGeeJayCee** [comment]
I've been doing this via mobile phone. 
I want to try via desktop but worried about throwing more gas fees away. Will unfed reimburse me on the previous ones?

**Comment by AgentGeeJayCee** [comment]
![image](https://user-images.githubusercontent.com/84189864/118396763-e9b84400-b648-11eb-8a5c-52826ed3dbe4.png)

Tx on my argent wallet as well x2

**Comment by AgentGeeJayCee** [comment]
![image](https://user-images.githubusercontent.com/84189864/118397179-a959c580-b64a-11eb-9305-064bc8bfb07c.jpeg)

This is on my Mac OS desktop

**Comment by AgentGeeJayCee** [comment]
I cleared cache on desktop and mobile but still showing borrowed amount

**Comment by vladyslav2** [comment]
@AgentGeeJayCee can you please send tx id here?

**Comment by AgentGeeJayCee** [comment]
Hi, I didn't realise that you had to enable payback as one transaction,then pay back as a second transaction. My fault,apologies

**Comment by hskainth** [comment]
Closing as non issue as per above comment
