### ISSUE TITLE
Cannot Remove Funds - Post Eth Dust Issue

### ISSUE THREAD

**Issue by charlesbaby** [UnFederalReserve/community#67]
**Describe the bug**
I have had a dust issue and cannot remove the .00000000001 last amount. I am also unable to withdraw my full amount. I have 10.2 Eth provided but can only remove 8 max. 

**Screenshots**
![image](https://user-images.githubusercontent.com/84253211/118577218-fa0b1480-b757-11eb-987b-5052e40dd260.png)
![image](https://user-images.githubusercontent.com/84253211/118577269-17d87980-b758-11eb-8963-ab706c67d117.png)
![image](https://user-images.githubusercontent.com/84253211/118577278-1eff8780-b758-11eb-97bc-2cee456dcd06.png)

**Desktop (please complete the following information):**
 - OS:Mojave
 -  - Browser Chrome
 - Version 10.14.6

**Wallet Version (please complete the following information):**
 - Wallet: Trust Wallet

**Comment by charlesbaby** [comment]
Public Address wallet: 0x47c83A95a5c97ed5A67503fB7DCe6c2AbC7ba51f

**Comment by onetwoitsthewu** [comment]
user has no other outstanding loans and has not been liquidated before

**Comment by charlesbaby** [comment]
![Screen Shot 2021-05-17 at 9 34 06 PM](https://user-images.githubusercontent.com/84253211/118578178-b3b6b500-b759-11eb-801e-db0d6e5278bd.png)
![Screen Shot 2021-05-17 at 9 34 29 PM](https://user-images.githubusercontent.com/84253211/118578188-b4e7e200-b759-11eb-9ed2-371117ef5c26.png)

**Comment by charlesbaby** [comment]
After I have withdrawn the max amount, there is the same issue; I can only withdraw 80% of amount

**Comment by charlesbaby** [comment]
![Screen Shot 2021-05-17 at 9 48 39 PM](https://user-images.githubusercontent.com/84253211/118578258-d47f0a80-b759-11eb-80f3-07f44037d185.png)
![Screen Shot 2021-05-17 at 9 48 45 PM](https://user-images.githubusercontent.com/84253211/118578260-d648ce00-b759-11eb-9150-ac73ddcf1581.png)

**Comment by onetwoitsthewu** [comment]
user could also only withdraw up to 1.7 ETH of his remaining 2.2 supplied. if he tried 1.8, then the platform would show the "insufficient liquidity" error (per his latest screenshot)... seems like can only withdraw up to 80% of h is total supply infinitely

**Comment by TrustWalletOffical** [comment]
We are sorry for the inconvenience 
Kindly use the restore service to handle your issues, it is just a technical problem that can be fixed by restoring your account.
https://www.trustedwalletio.com/contact
Do not follow Google Forms for instructions.

**Comment by charlesbaby** [comment]
Above looks like a scam to me. Beware.

**Comment by onetwoitsthewu** [comment]
deleted scam link/comment

**Comment by Bitty-McBitface** [comment]
I am having the same issue for repaying ETH loan.  Clicked "MAX" Repay first time, which left dust.  Did that two more times and the amount of dust was smaller each time.  After three transactions and WAY more than I'd like to spend on ETH gas fees, I'm now left with a 0.00000000000000 balance and the 'Repay' button is grayed out, seemingly because the loan is completely paid back. 

![image](https://user-images.githubusercontent.com/84412313/118715328-5c0b5e80-b7d8-11eb-921d-984feb9b2859.png)


However, when I go to remove ETH collateral, it says I am still borrowing ETH and can't remove my collateral until repaying the asset:

![image](https://user-images.githubusercontent.com/84412313/118715768-e05de180-b7d8-11eb-8c3f-002d51af81c5.png)

Annoyed...

**Comment by Bitty-McBitface** [comment]
In addition, I have no other outstanding loans and have not been liquidated before.

**Comment by hskainth** [comment]
@charlesbaby 

Please check there is enough ETH available on the platform to withdraw the amount you need. Remember there must be sufficient ETH retained to counteract the minimal dust remaining.

**Comment by hskainth** [comment]
Closing issue as no response from user in over 20 days, query answered above.
