### ISSUE TITLE
ETH dust when repaying loan

### ISSUE THREAD

**Issue by Bitty-McBitface** [UnFederalReserve/community#68]
I am having an issue repaying an ETH loan.  Clicked "MAX" Repay first time, which left dust.  Did that two more times and the amount of dust was smaller each time.  After three transactions and WAY more than I'd like to spend on ETH gas fees, I'm now left with a 0.00000000000000 balance and the 'Repay' button is grayed out, seemingly because the loan is completely paid back. 

![image](https://user-images.githubusercontent.com/84412313/118715328-5c0b5e80-b7d8-11eb-921d-984feb9b2859.png)

However, when I go to remove ETH collateral, it says I am still borrowing ETH and can't remove my collateral until repaying the asset:

![image](https://user-images.githubusercontent.com/84412313/118715768-e05de180-b7d8-11eb-8c3f-002d51af81c5.png)

Annoyed...

_Originally posted by @Bitty-McBitface in https://github.com/UnFederalReserve/community/issues/67#issuecomment-843516862_

**Comment by Bitty-McBitface** [comment]
This is what the borrow screen looks like: 

![image](https://user-images.githubusercontent.com/84412313/118732692-ae0bae80-b7ef-11eb-9c9f-ccd78b79f082.png)

**Comment by hskainth** [comment]
`Interest earned/accrued is automatically compounded per block. Completing any transaction (including withdrawal/repayment) requires a certain amount of blocks. While the transaction is being completed, new interest is going to be computed over the course of this operation. In the case of ETH, this is the fraction of the smallest decimal thus so-called “dust” is created.
ETH “dust” presents itself only with ETH supply/borrow and is prevalent across other Defi platforms.'
