### ISSUE TITLE
Max Withdrawal limits for staked ersdl and ETH

### ISSUE THREAD

**Issue by rwaynejoyce** [UnFederalReserve/community#69]
Recently tried to withdraw ETH - with 2 ETH staked, was only able to withdraw 0.89 ETH or 45% of the dollar value. Tested to see how much ersdl i could withdraw and was able to withdraw about 53% of the dollar value. Is this right? I was recently able to withdraw all of my stablecoin (DAI and USDC)

Current supply balance is $7.91k, current borrow balance - $712.21

ETH supply balance is $5,211.07 (not collateralized) and ersdl supply balance is $2697.29. Only borrowing ersdl. At 33% of borrow limit and my borrowed ersdl balance is $712.21

**Comment by hskainth** [comment]
@rwaynejoyce Please check markets page to see if there was sufficient supply available on platform for tokens.

**Comment by hskainth** [comment]
closing as non issue.

**Comment by rwaynejoyce** [comment]
Thank you - apologies I was not using your platform correctly
