### ISSUE TITLE
[resolved] claim rewards button not working until clearing cache

### ISSUE THREAD

**Issue by Director08** [UnFederalReserve/community#70]
**Describe the bug**
Another user and I both experienced this issue. When attempting to claim rewards, the "claim" button was unresponsive. Wondering if this was a browser specific issue, I attempted to claim rewards with Microsoft Edge, in addition to Chrome. Both browsers experienced the issue. Prior to submitting this to Github, I decided to clear my cache to see if that would fix the issue and it did. 

**To Reproduce**
I have not been able to reproduce this issue. 

**Expected behavior**
When claiming rewards the "claim" button should initiate a transaction through MetaMask to claim the distribution rewards that have accumulated. 

**Screenshots**
Not applicable, as this was a lack of a response on the platform. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 64-bit 
 - Browser - Chrome & Microsoft Edge
 - Version - Chrome (90.0.4430.212 (Official Build) (64-bit)) - Microsoft Edge (90.0.818.66 (Official build) (64-bit))

**Wallet Version (please complete the following information):**
 - Wallet: MetaMask
 - Public Address: 0xA57A4bbcdeD8C44cf106Eef5B45d815A81a5539D

**Additional context**
Since the issue was solved, it seems to be fine. However, I just wanted to add this to your radar.

**Comment by hskainth** [comment]
Internal issue #561 already raised internally for this.

**Comment by hskainth** [comment]
bug 561 resolved internally, closing as fixed.
