### ISSUE TITLE
Liquidated but still showing borrowed ersdl

### ISSUE THREAD

**Issue by Ronaldinho86** [UnFederalReserve/community#71]
Shouldn’t the borrowed ersdl be paid back once I was liquidated? I’m still showing borrowed ersdl. Do I still owe what is borrowed? I was liquidated on 5/23/2021. My wallet address is 

0xFD61E052E935D11F0D35a96CeC160348a8E1E35A

![Capture](https://user-images.githubusercontent.com/84891964/119769500-6b8d4600-be6f-11eb-8c6d-b16f458f8922.PNG)

Above is my up to date account on the platform. All of the supplied ersdl was transferred into my account after being liquidated, 

I do believe I shouldn't have been liquidated in the first place. I was trying to add more to my eth supply to bring my borrow limit percentage down but I was using the platform on my mobile and was unable to connect to metamask. I kept getting stuck on this screen. 

![photo_2021-05-26_21-59-09](https://user-images.githubusercontent.com/84891964/119768521-a1312f80-be6d-11eb-94da-16fee647c3ec.jpg)

I did leave this screen open for a long time with no luck. It never redirected me to metamask to approve the transaction. It's really upsetting being liquidated when I was on top of my limit percentage and was trying to add to my supply. I do not believe saying I shouldn't have been on mobile is an acceptable excuse. I was out of town and away from desktop. The majority of people work off of their mobiles. And to have this problem is a major issue.

**Comment by hskainth** [comment]
@Ronaldinho86 version is not fully supported on mobile yet as mentioned prior to release.

**Comment by Ronaldinho86** [comment]
I understand that. I know I'm screwed about the liquidation. Why am I still showing borrowed ersdl when I was liquidated? I originally had 47k ersdl supplied. I borrowed 17k ersdl. Once I was liquidated; all of my supplied ersdl went to zero. But my borrowed supplied still stayed the same. Shouldn't have the borrowed ersdl went to zero? I shouldn't have to pay back the borrowed ersdl since I was already liquidated. Please help!

**Comment by hskainth** [comment]
@Ronaldinho86  liquidation was done on the USDT, eRSDL was never repaid so will rightly shows as borrowed. Closing issue.

2 liquidations done:
Repaid 8210 usdt, seized 64914 ersdl
Repaid 5998 usdt, seized 6484 usdt
