### ISSUE TITLE
Question mark where my rewards used to be. 

### ISSUE THREAD

**Issue by dh3699** [UnFederalReserve/community#72]
**Describe the bug**
Question mark at the top of my screen where my rewards used to be. I have tried desktop and mobile versions, tried clearing the cache, tried completely uninstalling the browser and metamask and none of that has worked so far. In need of help to solve this problem. 
**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20210531-121313_Brave](https://user-images.githubusercontent.com/85139865/120250132-87a33580-c229-11eb-8d29-8feea5f42d29.jpg)

**Desktop (please complete the following information):**

**Wallet Version (please complete the following information):**
 - Wallet: [e.g. MetaMask, Coinbase]
 - Public Address: [e.g. 0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7]

**Additional context**

**Comment by hskainth** [comment]
internal issue 566 already raised for this issue on mobile only.

**Comment by dh3699** [comment]
> internal issue 566 already raised for this issue on mobile only.

How can I fix it?

**Comment by hskainth** [comment]
Closing as fixed rewards now show on side panel for mobile.
![image](https://user-images.githubusercontent.com/81052004/122676326-956b2b80-d1d5-11eb-9b06-80fbf1f36a63.png)
