### ISSUE TITLE
Can't Access LP stake 

### ISSUE THREAD

**Issue by Mrmiah98** [UnFederalReserve/community#73]
I am not able to access my staked LP tokens through the unfederal reserve site with my Trust Wallet.
I have tried multiple different devices and browsers and tried in other people's houses using different WiFi and mobile network. No success. The tokens show up on apy.vision
I have liaised with one of the telegram admins, Benn and he raised the issue to the team and wasn't able to solve the problem.

Could you please assist as I would like to access my coins as the LP staking is ending soon. 

Thank you

**Comment by hskainth** [comment]
@Mrmiah98 what is your ETH address?

**Comment by Mrmiah98** [comment]
0xAAFE14B4CA6D1f81FE1720D04e1A1438C829A24C

That's eth address I used to to stake.

**Comment by hskainth** [comment]
@Mrmiah98 Just to be clear -

- LP tokens are staked, these can only be accessed back in your wallet once you have un-staked
- The staked tokens will show up here [Menu > Select UnFederalReserve eRSDL] -
 
![image](https://user-images.githubusercontent.com/81052004/120832963-1d580100-c559-11eb-89fa-eb902d5e5b39.png)

Sounds like you are trying to access LP tokens that have already been staked but have not as yet been un-staked as such will not be visible in your wallet, please confirm.

**Comment by ryanmmmmm** [comment]
i see
<img width="768" alt="Screen Shot 2021-06-04 at 9 31 23 AM" src="https://user-images.githubusercontent.com/705959/120834283-a9e1cf80-c517-11eb-8550-4d6410370c82.png">


 tokens here:

https://etherscan.io/address/0xf8377270af0c864d2b3bab73bb16c65b05767549#readContract

<img width="781" alt="Screen Shot 2021-06-04 at 9 30 41 AM" src="https://user-images.githubusercontent.com/705959/120834202-90d91e80-c517-11eb-8ab8-88f12874410e.png">

**Comment by ryanmmmmm** [comment]
I would suggest using etherscan to withdraw then to see if that works?
https://etherscan.io/address/0xf8377270af0c864d2b3bab73bb16c65b05767549#writeContract

<img width="1330" alt="Screen Shot 2021-06-04 at 9 35 53 AM" src="https://user-images.githubusercontent.com/705959/120834727-473d0380-c518-11eb-8498-3f72269a6881.png">


PID is always 13.

you connect your wallet here: 

<img width="901" alt="Screen Shot 2021-06-04 at 9 36 40 AM" src="https://user-images.githubusercontent.com/705959/120834950-9125e980-c518-11eb-8385-b2aae854a6ba.png">

**Comment by Mrmiah98** [comment]
Thank you

I know they're there, the issue I can't access my staking through the ersdl site to claim rewards and unstake. When I connect my wallet it says my ersdl balance is 0.00 but I know I have some in my wallet.

**Comment by Mrmiah98** [comment]
Can I unstake and claim rewards through etherscan?

**Comment by Mrmiah98** [comment]
> @Mrmiah98 Just to be clear -
> 
> * LP tokens are staked, these can only be accessed back in your wallet once you have un-staked
> * The staked tokens will show up here [Menu > Select UnFederalReserve eRSDL] -
> 
> ![image](https://user-images.githubusercontent.com/81052004/120832963-1d580100-c559-11eb-89fa-eb902d5e5b39.png)
> 
> Sounds like you are trying to access LP tokens that have already been staked but have not as yet been un-staked as such will not be visible in your wallet, please confirm.
> 
> If you are trying to un-stake your staked LP tokens and are not able to, please confirm you have sufficient gas fee to carry out transaction. If you do then I can raise this internally for unstaking scenario.

Can you please raise this internally so I can unstake my coins? Thank you

**Comment by hskainth** [comment]
Internal issue 609 raised.

**Comment by hskainth** [comment]
@Mrmiah98 do you have a transaction hash you could provide us for your attempt to unstake?

**Comment by Mrmiah98** [comment]
I am not able to access the coins at all so haven't put through an unstake transaction

**Comment by hskainth** [comment]
@consta-l  terms still not visible -

![image](https://user-images.githubusercontent.com/81052004/120996813-94221380-c77e-11eb-9e91-c9b2a99dbb4c.png)

**Comment by Mrmiah98** [comment]
Is there any updates on this please?

**Comment by hskainth** [comment]
@Mrmiah98 we will update ticket once internal issue has been resolved.

**Comment by Mrmiah98** [comment]
Hi could you please update me ASAP. I am losing a lot ETH as my tokens stay in the LP

**Comment by hskainth** [comment]
@Mrmiah98  You can also try via etherscan:
https://etherscan.io/address/0xf8377270af0c864d2b3bab73bb16c65b05767549#writeContract
function deposit with 13 passed as pid and 0 as amount

<img width="680" alt="scan" src="https://user-images.githubusercontent.com/81052004/121915276-fb196c80-cd2a-11eb-8aff-25e7192edd6f.png">

**Comment by Mrmiah98** [comment]
Thank you. I've done that and it has claimed my eRSDL staking rewards. Now how do I remove my LP Tokens from staking as I still can't access them through the website?
Thanks again

**Comment by hskainth** [comment]
@Mrmiah98 Same place, different method: withdraw:
pid = 13
amount = 4837288879401828316

Amount is taken from the https://etherscan.io/address/0xf8377270af0c864d2b3bab73bb16c65b05767549#readContract
function userInfo

**Comment by Mrmiah98** [comment]
Thanks for all your help. Really appreciate. All done now
