### ISSUE TITLE
Cannot withdraw ETH from platform, nor fully repay a borrow

### ISSUE THREAD

**Issue by Derkaschnub** [UnFederalReserve/community#74]
**Describe the bug**
I am supplying approx 0.5 ETH and want to withdraw it. When I try to withdraw "max" and confirm through metamask, the transaction is "successful" on etherscan yet no ETH has moved from the platform to my wallet.

Additionally, when I try to shift the smileyface for ETH collateral to off, i recieve the message "You are borrowing this asset. In order to exit market you have to repay it first." When i check my borrow tab, it says "Currently Borrowing 4.8e-16 ETH" I have tried multiple times to max repay the borrow and am always left with ETH dust. I believe this may be related to the above issue.

**To Reproduce**
1. Go to "My Supply" (currently 0.5 ETH)
2. Click on 'ETH'
3. Click on "withdraw"
4. Click on "max",  displayed amount shows as approx 0.5 ETH as expected
5. Click on "confirm"
6. Metamask confirmation window appears, displayed number shows as "0" with "redeem" under it
7. Click confirm in metamask
8. Transaction completes, gas is consumed
9. No ETH has moved from the platform to my wallet. It remains in the platform.

**Expected behavior**
I expect the ETH to move to my wallet

**Screenshots**
![image](https://user-images.githubusercontent.com/85719737/121627000-8a313680-ca44-11eb-9c6a-1cedbb5b7564.png)
![image](https://user-images.githubusercontent.com/85719737/121627031-9d440680-ca44-11eb-8c02-ca9088e1d467.png)

**Desktop (please complete the following information):**
Google Chrome

**Wallet Version (please complete the following information):**
 - Wallet: MetaMask
 - Public Address: [0x7872199A1019EF80420e19D68Aca78FDed71F035]

**Additional context**
I am not able to withdraw ANY amount of ETH.

**Comment by hskainth** [comment]
Interest earned/accrued is automatically compounded per block. Completing any transaction (including withdrawal/repayment) requires a certain amount of blocks. While the transaction is being completed, new interest is going to be computed over the course of this operation. In the case of ETH, this is the fraction of the smallest decimal thus so-called “dust” is created. ETH “dust” presents itself only with ETH supply/borrow and is prevalent across other Defi platforms.

**Comment by Derkaschnub** [comment]
I am still not able to withdraw anything from my supplied assets. The platform allows me to complete withdraw transactions and use gas, yet no funds are moving.

https://etherscan.io/tx/0x4455c1ae8a3d085c68ed6115eac4c5c0606fc45b674cca4fa8b20f3cb599f0e6

Here is my latest attempt. As you can see, the value is 0 ETH, although the platform previewed the value as 0.5 ETH
