### ISSUE TITLE
LP stuck in old staking farm

### ISSUE THREAD

**Issue by SpitStonks** [UnFederalReserve/community#75]
Every time I try to connect my wallet through app.unfederalreserve.com/farms to remove my LP and rewards, it gets stuck on the loading screen and never changes. When I click my wallet in the top right, it shows 0s across the board, but the view on etherscan button takes me right to the correct wallet address 0xcAC9946443BDAb6058676925d2D2Ed9024d478e3. Anyone know what's happening here or how I can fix this issue? 

I'm currently using Trust Wallet and i've tried it with Chrome, Brave, Firefox and IE.

**Comment by hskainth** [comment]
@SpitStonks please see comments in closed bug #73 simply replace values with the values found in your contract you should be able to get your LP back via this.

**Comment by SpitStonks** [comment]
Thank you, that worked wonders and even though it was the first time I've worked through etherscan, it went through smooth as butter. Appreciate your help.

**Comment by MaxCJ7** [comment]
Hello, I'm having the same issue and am going to try this... what do you mean by the values found in my contract?

**Comment by MaxCJ7** [comment]
@hskainth Please see comment I left above - I see how to do it on Etherscan but am not entirely sure what values to input
