### ISSUE TITLE
Supplied asset incorrectly showing $0 APY earned

### ISSUE THREAD

**Issue by tdizzletheschizzle** [UnFederalReserve/community#78]
**Describe the bug**
On lending.unfederalreserve.com, it shows $0 for APY earned in the 'my supply's section.  This is only for ETH (eRSDL and USDC are showing correctly).  This seems to be new and was not the case last time I checked.  My ETH has been supplied since right after product launch.

**To Reproduce**
1. Go to lending.unfederalreaerve.com
2. Click on 
3. Scroll down to 'my supply'

**Expected behavior**
It should show more than $0

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.106

**Wallet Version (please complete the following information):**
 - Wallet: MetaMask
 - Public Address: 0x811d1eBe6543DC59eC97b7778A5a381489415c95

**Additional context**

**Comment by hskainth** [comment]
@tdizzletheschizzle what do you see when you hover over the value?

**Comment by tdizzletheschizzle** [comment]
The display bug seemed to resolve itself (an amount was showing finally), and I moved all ETH off the platform so I can't report any further.  However, I will say that I'm now experiencing the same issue with my supply of eRSDL.  The APY earned is displaying $0.

**Comment by hskainth** [comment]
Internal issue 687 raised.

**Comment by hskainth** [comment]
@tdizzletheschizzle how much eRSDL did you supply?

**Comment by tdizzletheschizzle** [comment]
Approx 330K eRSDL

**Comment by hskainth** [comment]
@tdizzletheschizzle if you try CTRL, SHIFT and R , do you still see this issue?

**Comment by hskainth** [comment]
We have tried on both internal and live environments and it is generating fine for us.

**Comment by hskainth** [comment]
Closing issue as no response from user in over 2 weeks and issue not seen internally.
