### ISSUE TITLE
Supplied APY incorrectly showing $0

### ISSUE THREAD

**Issue by joemk88** [UnFederalReserve/community#79]
Describe the bug
On lending.unfederalreserve.com, it shows $0 for APY earned in the 'my supply's section. This is only for ETH (wBTC is showing correctly). This seems to be new and was not the case last time I checked. My ETH has been supplied for about a week.
The balance seems correct (still accumulating interest and rewards, just not displaying correctly)

To Reproduce

    Go to lending.unfederalreaerve.com
    Click on
    Scroll down to 'my supply'
    See error

Expected behavior
It should show more than $0

Screenshots
![Screenshot_2021-06-16_22-30-16](https://user-images.githubusercontent.com/70954873/122149004-b7e00a80-ce9e-11eb-8580-b66f63e82f7f.png)

Desktop (please complete the following information):

    OS: Windows 10
    Browser Chrome
    Version 91.0
and 
    OS: Linux MX
    Browser Firefox
    Version 89.0

Wallet Version (please complete the following information):

    Wallet: MetaMask
    Public Address: 0x8bBD70014Fea6e01801046CBd173E640f8182f8f

Additional context

**Comment by hskainth** [comment]
@joemk88 Supply APY at time of writing is 2.04% on platform your rewards, what is the value shown when you hover over the displayed value?

**Comment by joemk88** [comment]
> @joemk88 Supply APY at time of writing is 2.04% on platform your rewards, what is the value shown when you hover over the displayed value?

The issue has been fixed. It's currently showing 2.24% and reflecting correct dollar amount of APY earned.
Cheers

**Comment by hskainth** [comment]
Closing issue as fixed.
