### ISSUE TITLE
Cannot repay eRSDL loan via Argent Wallet

### ISSUE THREAD

**Issue by AgentGeeJayCee** [UnFederalReserve/community#80]
**Describe thebug
Trying to repay loan via Argent wallet. Trx goes through but loan not repaid. 
**To Reproduce**
1. Approve amount to pay on Argent
2. Set limit to pay
3. Input amount to pay on Argent
4. Wait for trx to go through
5. Trx successful on etherscan but loan 
Not repaid and gas fee taken

**Expected behavior**
Loan to be repaid
**Screenshots**
![image](https://user-images.githubusercontent.com/84189864/122289335-812fe180-ceea-11eb-9de9-837ec0785964.png)
![image](https://user-images.githubusercontent.com/84189864/122289382-8ee56700-ceea-11eb-9002-4458d0755fe9.png)
**Desktop (please complete the following information):**
 - Argent wallet on iPad safari browser 
iMac on safari

**Wallet Version (please complete the following information):**
 - Wallet: argent via wallet connect
 - Public Address: 0xe533361D20Df1c0A575C87493418Bd62c26Bba06

**Additional context**

**Comment by AgentGeeJayCee** [comment]
![image](https://user-images.githubusercontent.com/84189864/122289961-2d71c800-ceeb-11eb-9d6e-529ecc3e9f5c.png)

**Comment by AgentGeeJayCee** [comment]
Resolution found, please close

**Comment by hskainth** [comment]
Closing issue as resolved.
