### ISSUE TITLE
unique issue unstaking USDC from lending platform

### ISSUE THREAD

**Issue by stinkycubert** [UnFederalReserve/community#82]
Hey guys! I have talked extensively to a few mods on the telegram about this and tried to the obvious solutions, but none have worked so far.

Yesterday I decided to take my USDC out of My Supply. My transaction was successful, but it did not move to my wallet and instead remained in My Supply on the dapp. I have tried a total of 4 times now. Each time the transaction succeeds, my eth is paid, and the tokens do not appear. I can see on the contract there is plenty of USDC.  The first 3 attempts were done in Chrome, while the 4th i tried Brave browser and got the same results.

I will share the TXs in order.

1. https://etherscan.io/tx/0x0caae49183eca6f38141a599d0f188742218ede02d6174c6674e7f6297e95a03
2. https://etherscan.io/tx/0x2594b428cc572fc360bb847778d277ce133ff356916b422d3582828b409069f4
3. https://etherscan.io/tx/0x2594b428cc572fc360bb847778d277ce133ff356916b422d3582828b409069f4
4. https://etherscan.io/tx/0x5bbac247f310bd15cce197d6878a46ef11e0cfac3e41f1cacad72476c20767fe

I have taken USDC off the platform in the recent past without issue so I found this surprising.  I have been a longtime advocate of eRSDL since November and very active in the community, I believe in the project, I'm being patient as I know there are a lot of issues with USDT going on. I would love to get this fixed and let everyone know how diligently you all worked on this! The irony is I was simply taking out my stable to buy more eRSDL!

Thank you!

Windows 10
Chrome, brave browser
Ledger (through metamask)
address: 0x655f20b480412ca1d9dcac2d9954ece821a126e3

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Wallet Version (please complete the following information):**
 - Wallet: [e.g. MetaMask, Coinbase]
 - Public Address: [e.g. 0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7]

**Additional context**

**Comment by hskainth** [comment]
Internal issue #672 raised for this to investigate.

**Comment by hskainth** [comment]
@stinkycubert  it appears as there was not enough USDC on platform to withdraw -

![image](https://user-images.githubusercontent.com/81052004/122559594-7040b680-d037-11eb-9230-8f4c53c5dfe3.png)
