### ISSUE TITLE
Can't connect Trust Wallet via Wallet Connect

### ISSUE THREAD

**Issue by Deewil** [UnFederalReserve/community#83]
**Describe the bug**
Can't connect Trust Wallet to Lending Platform via wallet connect

**To Reproduce**
1. Go to Lending Platform
2. Click on 'Connect Wallet
3. Scan QR code

**Expected behavior**
Error Message

**Screenshots**
![Screenshot_20210622-094458](https://user-images.githubusercontent.com/86297945/122914847-62eb3b00-d35b-11eb-924c-8b2e76cb0b53.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 

**Wallet Version (please complete the following information):**
 - Wallet: Trust
![Screenshot_20210622-094458](https://user-images.githubusercontent.com/86297945/122914796-4fd86b00-d35b-11eb-967a-ba4d4cee48ff.png)

 - Public Address: [e.g. 0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7]

**Additional context**

**Comment by hskainth** [comment]
Linked to internal issue 691

**Comment by hskainth** [comment]
Closing issue as fixed internally.
