### ISSUE TITLE
Not earning eRSDL since claiming rewards

### ISSUE THREAD

**Issue by Faisven22** [UnFederalReserve/community#85]
Hello I have a problem with the lending platform

I'm staking since release

Two weeks ago I repaid my ersdl loan and withdrawed my earnings

But I am suppling wbtc and eRSDL since the start and I don't earn anything since I withdraw my rewards two weeks ago

I know the APY is low for ersdl but I assume 2 weeks would be a minimum of 0.1 ersdl I am supplying nearly 30k ersdl and 0,03 WBTC

I don´t know how to reproduce the bug, i cleared my cache and it won´t work

I don´t know how the solve the problem either

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 

**Wallet Version 
 - Wallet: Metamask
 - Public Address: 0x83A1a09FFD4CD72Bc7D7d429234271bD40542350

hopefully someone can help i´m supplying for nothing atm.

Sincerly Faisven22
![ersdl 1](https://user-images.githubusercontent.com/84814475/123864935-99145600-d92b-11eb-9b3c-1da721808a1a.PNG)
![ersdl 2](https://user-images.githubusercontent.com/84814475/123864946-9c0f4680-d92b-11eb-9941-5a4c4ada22ea.PNG)

**Comment by hskainth** [comment]
@Faisven22 What value do you see when you hover the mouse over the eRSDL APY/Earned value?

**Comment by Faisven22** [comment]
i don´t see any value, only on Wbtc and the ETH dust

________________________________
Von: Harinder ***@***.***>
Gesendet: Mittwoch, 30. Juni 2021 10:26
An: UnFederalReserve/community ***@***.***>
Cc: Faisven22 ***@***.***>; Mention ***@***.***>
Betreff: Re: [UnFederalReserve/community] Not earning eRSDL since claiming rewards (#85)


@Faisven22<https://github.com/Faisven22> What value do you see when you hover the mouse over the eRSDL APY/Earned value?

**Comment by hskainth** [comment]
@Faisven22  in the tool tip pop up as below ?

![image](https://user-images.githubusercontent.com/81052004/124258771-aeed6b00-db25-11eb-9b62-f95ee6a2a3b7.png)

**Comment by Faisven22** [comment]
![image](https://user-images.githubusercontent.com/84814475/124402343-f8a9a180-dd2f-11eb-9680-5b5c688d5caf.png)


as you can see on the screenshot it shows zero

**Comment by hskainth** [comment]
Internal issue 772 raised to investigate.

**Comment by Faisven22** [comment]
it was only an UI bug, maybe you can fix this but no mayor problem i will close this ticket now thx anyways:)
