### ISSUE TITLE
Adding to staking overwrote the previous balance and earnings. 

### ISSUE THREAD

**Issue by theemrbucky** [UnFederalReserve/community#86]
**Describe the bug**
I added funds to my staking account and it overwrote the previous stake earnings and deposit. I don't remember what the previous balance was unfortunately but I know it wasn't what was showing currently. 

**Expected behavior**
I thought my additional funds would just be added to the current balance and displayed. 

**To Reproduce**

**Screenshots**
I don't think my screenshots would help.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.4
 - Browser - Chrome 
 - Version - 91.0.4472.114 (Official Build) (x86_64)

**Wallet Version (please complete the following information):**
 - Wallet: MetaMask
 - Public Address: 0x7f38A8aa96697f0BEB1FD8887B0f68D229E92704

**Additional context**
I didn't unstake my previous balance or harvest any of the earnings. This is what my current balance indicates: 
Balance before emitting coins - 97.635
4.929 - Earned
2.541 - LP tokens staked

I was able to find the two hash address things for my initial deposits but I'm not tech enough to understand it beyond anything else. Here they are: 
0x1e4934418094655e561a6e3e0eb209c80741cecc76a1c44c32df14a2b2ae9fcf
0x451f606e00452e7a37c97cb5e1cf2151692946a9acbdb876af36de84442c0b36
I paired the tokens through Uniswap v2. (I'm pretty sure it was v2)

Thanks,
-Bucky

**Comment by harv-singh** [comment]
749 Issue internally raised

**Comment by hskainth** [comment]
@theemrbucky Closing issue as adding additional LP tokens harvests current rewards at the same time.
