### ISSUE TITLE
"Max" button during supply / deposit is malfunctioning

### ISSUE THREAD

**Issue by CryptoBiased** [UnFederalReserve/community#88]
**Describe the bug**
The "MAX" button on both SUPPLY features (lending homepage AND /market-details) for assets is failing.  The button currently maxes out at current available market liquidity rather than available wallet balance.

**To Reproduce**
1. Go to 'https://lending.unfederalreserve.com/market-details/USDT'
2. Click on 'MAX' with wallet connected and USDT available
3. Take note of MAX deposit/supply value as compared to both wallet balance AND market liquidity. (see screenshot)

**Expected behavior**
MAX button should max out at wallet balance of asset.

**Screenshots**
![image](https://user-images.githubusercontent.com/72321338/125532768-6071c816-d588-4fdb-9459-5ad8977e9c90.png)

**Desktop (please complete the following information):**
 - OS: Win10 / Also tested iOS latest on iPhone
 - Browser Chrome

**Wallet Version (please complete the following information):**
 - Wallet: MetaMask
 - Public Address: n/a

**Additional context**

**Comment by ryanmmmmm** [comment]
deposits DO 100% vwork however this is a max button issue...  will get addressed today

**Comment by hskainth** [comment]
Internal bug 798 raised to investigate this issue.

**Comment by hskainth** [comment]
Bug 798 verified as fixed internally. Closing issue
