### ISSUE TITLE
Cannot ETH withdraw supply back to wallet

### ISSUE THREAD

**Issue by Derkaschnub** [UnFederalReserve/community#89]
Describe the bug

ETH Dust: Because the platform does not allow me to repay the remaining 0.0000000000001 ETH that I have borrowed, I am not able to withdraw my supplied ETH.

To Reproduce

Go to "My Supply" (currently 0.5 ETH)
Click on 'ETH'
Click on "withdraw"
Click on "max", displayed amount shows as approx 0.5 ETH as expected
Click on "confirm"
Metamask confirmation window appears, displayed number shows as "0" with "redeem" under it
Click confirm in metamask
Transaction completes, gas is consumed
No ETH has moved from the platform to my wallet. It remains in the platform.
Expected behavior
I expect the ETH to move to my wallet

![image](https://user-images.githubusercontent.com/85719737/126254627-4bc13986-57d0-4e9b-bec5-46e4543971f5.png)

Desktop (please complete the following information):
Google Chrome

Wallet Version (please complete the following information):

Wallet: MetaMask
Public Address: [0x7872199A1019EF80420e19D68Aca78FDed71F035]
Additional context
I am not able to withdraw ANY amount of ETH.

**Comment by hskainth** [comment]
@Derkaschnub as mentioned before please try to withdraw an amount that is not max and an amount less than what is staked against borrowed. This will work.

**Comment by Derkaschnub** [comment]
sounds good thanks
