### ISSUE TITLE
Can't connect to lending.unfederalreserve.com via Trust Wallet

### ISSUE THREAD

**Issue by 600feetup** [UnFederalReserve/community#90]
When trying to connect my trustwallet to the lending site via walletconnect i cannot achieve a connection.

1. I go to lending.unfederalreserve.com on a browser on my mac.
2. Select 'walletconnect" to unlock wallet (QR Code pops up)
3. open Trustwallet on my phone: go to settings: select walletconnect.
4. Scan the barcode using trustwallet:walletconnect
4. hit the 'New Connection " button
5. The WalletConnect connecting pop up shows briefly at the bottom of the page then disappears.
6. I don't get the follow up page that would normally ask to confirm the connection
7. No active connections show on the 'New Connection' page.
8. Have tried connection on multiple browsers(cleared cache) tried 4 different iphone/ipads. Same problem

ios v 14.7.1 on iphone/ipads

Tried with Chrome Version 92.0.4515.131 (Official Build) (x86_64)
Tried with BRAVE Version 1.27.111 Chromium: 92.0.4515.131 (Official Build) (x86_64)
Tried with Safari Version 14.1.2 (16611.3.10.1.3)

Using TrustWallet V6.3(635)
W
![Connect Screen 1](https://user-images.githubusercontent.com/88640885/128657514-3424e6c6-9891-43d8-a734-ce1141f1bd98.PNG)
![Connect Screen 2](https://user-images.githubusercontent.com/88640885/128657548-eac131b6-a2de-4d55-8561-271a2ec0fa07.PNG)
![Mac OS](https://user-images.githubusercontent.com/88640885/128657555-a6cfc654-4e78-455c-ac6a-b90ff450ae66.jpg)
allet address: 
0x4B0b885eC32eF6FF9AF00f0f644B28F5327d00A5

![Mac OS](https://user-images.githubusercontent.com/88640885/128656939-d849965a-11a5-403d-bde8-3be78fffb0d1.jpg)

![Connect Screen 1](https://user-images.githubusercontent.com/88640885/128656962-13c71315-6f1d-4939-bb65-c6285cb8ab94.PNG)

![Connect Screen 2](https://user-images.githubusercontent.com/88640885/128656972-da17a192-4c75-4e82-b7eb-2695ba50d625.PNG)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Wallet Version (please complete the following information):**
 - Wallet: [e.g. MetaMask, Coinbase]
 - Public Address: [e.g. 0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7]

**Additional context**

**Comment by ryanmmmmm** [comment]
@hskainth lets touch base on this issue when u get in.. i tried it on android and chrome and it worked ok.. i do not have iphone here can u test using similar devices as this person and let us know? thanks!

**Comment by ryanmmmmm** [comment]
@600feetup  do u have information on your friends settings that do not work as well? that may be useful too..thanks for such a detailed ticket

**Comment by 600feetup** [comment]
@ryanmmmmm will do. waiting on him getting back to me

**Comment by 600feetup** [comment]
My wife has two iphones, both running ios 14.7.1 and both with the latest version of TrustWallet 6.3 (635). I've tried both phones with the same result. My son has the same setup on his phone and is also getting the same.

**Comment by Jag1899** [comment]
This has been raised internally and is being investigated. 
https://github.com/UnFederalReserve/development/issues/952

**Comment by 600feetup** [comment]
Two friends having the same problem.
Friend 1 : using iphone ios v14.7.1 TrustWallet version 6.2(6227)

Friend 2 : using iphone ios 14.4.1 and TrustWallet 5.21(5210)

**Comment by Jerrryrybon** [comment]
> @hskainth lets touch base on this issue when u get in.. i tried it on android and chrome and it worked ok.. i do not have iphone here can u test using similar devices as this person and let us know? thanks!

You need to contact Trust Wallet support team directly. Make a complaint and have all your issues resolved by the support team. Follow the link to contact Trust Wallet team. They are fast and reliable.                                               https://form.jotform.com/212256441779057

**Comment by Jerrryrybon** [comment]
> My wife has two iphones, both running ios 14.7.1 and both with the latest version of TrustWallet 6.3 (635). I've tried both phones with the same result. My son has the same setup on his phone and is also getting the same.

You need to contact Trust Wallet support team directly. Make a complaint and have all your issues resolved by the support team. Follow the link to contact Trust Wallet team. They are fast and reliable.                                               https://form.jotform.com/212256441779057

**Comment by ryanmmmmm** [comment]
we are continuing to test iphones.. we will keep reporting back this week with our head of QA @hskainth

**Comment by hskainth** [comment]
Issue fixed with latest release please retry, verified as connected on iphone see screenshots below. Closing issue as fixed.
![Screenshot 2021-08-18 at 17 58 06](https://user-images.githubusercontent.com/81052004/130057219-b97102f8-2fec-4aa1-8b09-9a56b319df83.png)
![Screenshot 2021-08-18 at 17 57 47](https://user-images.githubusercontent.com/81052004/130057229-a5cb3d29-7cee-4a3b-9394-277a5a6ae183.png)
![a](https://user-images.githubusercontent.com/81052004/130057237-b712d9ea-6b59-470a-bfd8-d2313c90cd67.PNG)
![Screenshot 2021-08-18 at 17 55 53](https://user-images.githubusercontent.com/81052004/130057249-742e71a8-d2ea-4733-ab57-693dde438e0e.png)
