### ISSUE TITLE
Cannot withdraw eRSDL from lending page

### ISSUE THREAD

**Issue by suntzuwong** [UnFederalReserve/community#91]
**Describe the bug**
Cannot withdraw eRSDL from lending page. Did the tx twice and nothing.
If i try to do whole number the button is greyed out

**To Reproduce**
1. Go to '...' https://lending.unfederalreserve.com/
2. Click on '....' Under SUPPLY, click on eRSDL
3. Scroll down to '....' Click WITHDRAW, MAX, WITHDRAW
4. See error TX goes thru, twice, but my tokens are still on the platform

**Expected behavior**
I expected to get my tokens back

<img width="1680" alt="Screen Shot 2021-08-17 at 7 11 56 AM" src="https://user-images.githubusercontent.com/33138251/129806932-9a9cb7fa-464b-4e5a-874d-38dcff3118cf.png">
<img width="1680" alt="Screen Shot 2021-08-17 at 7 11 47 AM" src="https://user-images.githubusercontent.com/33138251/129806948-58a8ad08-d65f-435d-88ff-9188601c70d8.png">
<img width="1680" alt="Screen Shot 2021-08-17 at 7 08 55 AM" src="https://user-images.githubusercontent.com/33138251/129806951-bed541c6-78a3-4085-8403-fdae1fb409a6.png">

**Screenshots**

**Desktop (please complete the following information):**

**Wallet Version (please complete the following information):**
 - Wallet: [e.g. MetaMask, Coinbase]  metamask
 - Public Address: [e.g. 0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7] dragongate.eth

**Additional context**

ACTUALLY, i just withdrew the my tokens but had to reduce the decimals to .000
Whole numbers dont' work. 
Withdraw with MAX with 9 decimals or so wont work.

**Comment by harv-singh** [comment]
Hi @suntzuwong just wanted to confirm the issue here:
- Were you able to withdraw eRSDL in the end?
- Was the issue that the Supply button being greyed out?


Thanks

**Comment by hskainth** [comment]
@suntzuwong this is not an issue, you have fractional eRSDL locked up against your ETH borrowing dust so you will not be able to withdraw complete amount, as you stated you were able to withdraw remaining amount.  Closing as non issue.
