### ISSUE TITLE
Problem Withdrawing Funds despite Shown Available Liquidity

### ISSUE THREAD

**Issue by Marialaina12** [UnFederalReserve/community#96]
2 Issues actually:

1. I tried to remove my DAI from my account because I say 36K of liquidity was available. I willed out withdrawal form and clicked max and it looked like transaction was going through...it even got confirmed but no DAI in my wallet. Then I thought well maybe that was initial approval even though gas cost was $229 so I did the withdrawal transaction again and same thing....no DAI withdrawn even though transaction confirmed. Of course now there is no liquidity . I just didn't want to lose $450 worth of ETH. For some reason The transcation did not register that I wanted to withdraw anything....says 0 ETH. 
Here are Transaction numbers
0x3759d6381b37dc3b9005263069fd60a9d4d8c4e75b2f496c0dacf9f4e948ec91
0xe2c0f180ecd36b72190533ae985473ecc7e89474fd08306595fbbec2afa98a91

2. The second issue is I had an ETH loan which Ithought  paid back in full because I clicked the max button when I paid it...but it was still showing a balance...so I tried again to pay back the full amount and after confirming....I staill have a balance. So max button is not working. I should have had it paid off the first time...and since I still have a balance...will not be able to withdraw all my funds if I want. Thanks so much for all your assistance.

**Comment by hskainth** [comment]
@Marialaina12 

1. It appears that ETH loan was taken out against DAI as collateral hence a fractional amount would be required to remain to counteract against borrow ETH dust remaining below. Manually entering an amount minus ETH dust amount would have allowed liquidity to be withdrawn.

2. `Interest earned/accrued is automatically compounded per block. Completing any transaction (including withdrawal/repayment) requires a certain amount of blocks. While the transaction is being completed, new interest is going to be computed over the course of this operation. In the case of ETH, this is the fraction of the smallest decimal thus so-called “dust” is created.
ETH “dust” presents itself only with ETH supply/borrow and is prevalent across other Defi platforms.'

Closing as non issue.
