### ISSUE TITLE
Problem Withdrawing Funds.

### ISSUE THREAD

**Issue by Marialaina12** [UnFederalReserve/community#97]
I am trying again to withdraw some of my DAI. But in MM when I go to confirm transaction...it shows I am withdrawing 0 ETH....and only the ETH fee.  There is liquidity present and I accounted for the "dust" from my previous ETH loan. I don't want to send transaction because the last two I sent showing a 0 ETH and only a gas fee on MM I didn't get any DAI. 
Is it normal for 0 ETH to show in MM? I don't want to waste anymore gas....A friend also tried to withdraw and saw the 0 ETH...he didn't complete the transaction though because of gas fees. Thanks so much!!

![Screen Shot 2021-09-07 at 8 47 27 AM](https://user-images.githubusercontent.com/90158921/132350496-b56c6cd1-c70c-4e92-98d7-0cdd38aa6526.png)

![Screen Shot 2021-09-07 at 8 50 37 AM](https://user-images.githubusercontent.com/90158921/132350515-1ac15600-0fdf-4a81-b405-4926b73fd2e2.png)

![Screen Shot 2021-09-07 at 8 51 00 AM](https://user-images.githubusercontent.com/90158921/132350544-d99bcfbf-ab4e-4229-ae8b-e49735c7f233.png)

**Comment by hskainth** [comment]
@Marialaina12 0 ETH means that user is not sending any ETH in this transaction, this is correct. 

There should be no issues with withdrawing if there is enough liquidity available on the platform at time of withdrawal, currently platform shows the below available liquidity for Dai -

![image](https://user-images.githubusercontent.com/81052004/132495527-d9a50bc9-d2b8-41ab-8a0f-b74f7c97de56.png)

**Comment by hskainth** [comment]
Closing issue as resolved as no response.
