### ISSUE TITLE
Unable to access my assets on the platform. 

### ISSUE THREAD

**Issue by teamcryptousa** [UnFederalReserve/community#98]
**Describe the bug**
I normally link to UnFederalReserve lending platform via Trust wallet. I tried loggin in on 2 devices and it's saying "no assets supplied." I have the unfederalreserve assets in my wallet. Nothing is displaying on the platform. 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/82060595/132913127-860dddbe-8020-417f-9efa-5009ff504004.png)

**Desktop (please complete the following information):**
 - OS: Tried on Chrome and Safari
 - Browser Chrome and Safari

**Wallet Version (please complete the following information):**
 - Wallet: Trust Wallet
 - Public Address: 0x9975653EcfA9a4409DC291E67Ba938C5B7366092

**Additional context**

**Comment by hskainth** [comment]
@teamcryptousa thanks for reporting issue, internal issue 1209 has been raised for this.

**Comment by fizzyfoss26** [comment]
Any updates here?

**Comment by teamcryptousa** [comment]
I still don’t have access today

**Comment by hskainth** [comment]
@fizzyfoss26 @teamcryptousa are you still experiencing this as we cannot reproduce?

**Comment by teamcryptousa** [comment]
No. It’s working now. Thanks for the follow up.

**Comment by hskainth** [comment]
Closing issue as per above comment.

**Comment by teamcryptousa** [comment]
My supplied USDC isn't showing up in my wallet again. It's been going on
for a couple of days. This is the second time this has happened. Can you
please look at it?
My Wallet Address is:

0x9975653EcfA9a4409DC291E67Ba938C5B7366092

[image: image.png]

**Comment by hskainth** [comment]
@teamcryptousa this should now show.

**Comment by teamcryptousa** [comment]
It's working now. Thank you.
